import type { Module, TopicId } from "./catalog";
export type DeepSpec = {
  input: string;
  min: number;
  max: number;
  initial: number;
  variants: [string, string][];
  examples: { title: string; why: string; quantity: number; variant: string }[];
};
const spec = (
  input: string,
  min: number,
  max: number,
  initial: number,
  variants: [string, string][],
  examples: DeepSpec["examples"],
): DeepSpec => ({ input, min, max, initial, variants, examples });
const ex = (title: string, why: string, quantity: number, variant: string) => ({
  title,
  why,
  quantity,
  variant,
});
export const deepSpecs: Record<string, DeepSpec> = {
  "load-balancing": spec(
    "Number of incoming jobs",
    3,
    12,
    6,
    [
      ["round-robin", "Round robin"],
      ["least-work", "Least queued work"],
    ],
    [
      ex(
        "Equal rotation",
        "Each server gets a turn, even if earlier work was expensive.",
        6,
        "round-robin",
      ),
      ex(
        "Work-aware routing",
        "Route to the smallest sum of queued service time.",
        6,
        "least-work",
      ),
      ex(
        "Longer burst",
        "Compare job counts with actual queued work.",
        12,
        "least-work",
      ),
    ],
  ),
  "cache-invalidation": spec(
    "New database value",
    1,
    100,
    20,
    [
      ["ttl", "TTL only"],
      ["invalidate", "Invalidate on write"],
    ],
    [
      ex(
        "Stale cached read",
        "A write does not automatically refresh a cache.",
        20,
        "ttl",
      ),
      ex(
        "Invalidate then refill",
        "The next reader fetches the updated database value.",
        20,
        "invalidate",
      ),
      ex(
        "Different update",
        "Trace the same policy with a different value.",
        70,
        "invalidate",
      ),
    ],
  ),
  "replication-lag": spec(
    "Replication delay (ticks)",
    1,
    6,
    3,
    [
      ["replica", "Read from replica"],
      ["leader", "Read from leader"],
    ],
    [
      ex(
        "Read before replication",
        "A replica can serve an older committed version.",
        3,
        "replica",
      ),
      ex(
        "Read your write",
        "Send the read to the leader in this model.",
        3,
        "leader",
      ),
      ex("Short lag", "See the replica catch up sooner.", 1, "replica"),
    ],
  ),
  "rate-limiting": spec(
    "Bucket capacity (tokens)",
    1,
    8,
    3,
    [
      ["burst", "Burst arrivals"],
      ["steady", "Steady arrivals"],
    ],
    [
      ex(
        "Burst exceeds budget",
        "Tokens bound immediate acceptance.",
        3,
        "burst",
      ),
      ex(
        "Steady replenishment",
        "One new token arrives each tick.",
        3,
        "steady",
      ),
      ex(
        "Larger burst allowance",
        "A larger bucket admits more of the initial burst.",
        6,
        "burst",
      ),
    ],
  ),
  "sql-aggregation": spec(
    "HAVING minimum group total",
    0,
    300,
    100,
    [
      ["sum", "SUM(amount)"],
      ["count", "COUNT(*)"],
    ],
    [
      ex(
        "Filter grouped totals",
        "Compare groups before and after HAVING.",
        100,
        "sum",
      ),
      ex("Count orders", "Count measures rows, not money.", 2, "count"),
      ex(
        "Keep every group",
        "A zero threshold preserves every group.",
        0,
        "sum",
      ),
    ],
  ),
  "composite-index": spec(
    "Minimum order amount",
    0,
    200,
    80,
    [
      ["customer-first", "Index (customer, amount)"],
      ["amount-first", "Index (amount, customer)"],
    ],
    [
      ex(
        "Equality then range",
        "Matching customer keys form one contiguous range.",
        80,
        "customer-first",
      ),
      ex(
        "Range then equality",
        "The amount range also includes other customers.",
        80,
        "amount-first",
      ),
      ex(
        "Selective amount",
        "Compare fewer candidates with a higher threshold.",
        150,
        "amount-first",
      ),
    ],
  ),
  "transaction-isolation": spec(
    "Concurrent committed increment",
    1,
    50,
    10,
    [
      ["read-committed", "Read committed"],
      ["snapshot", "Snapshot reads"],
    ],
    [
      ex(
        "Nonrepeatable read",
        "The second statement sees a newer committed value.",
        10,
        "read-committed",
      ),
      ex(
        "Stable snapshot",
        "Both reads use the transaction’s original snapshot.",
        10,
        "snapshot",
      ),
      ex(
        "Larger concurrent write",
        "Committed storage changes even when the snapshot stays stable.",
        30,
        "snapshot",
      ),
    ],
  ),
  "virtual-memory": spec(
    "Virtual address",
    0,
    31,
    13,
    [
      ["mapped", "Page 3 is mapped"],
      ["fault", "Page 3 is absent"],
    ],
    [
      ex(
        "Translate an address",
        "Split the address into page number and offset.",
        13,
        "mapped",
      ),
      ex(
        "Handle a page fault",
        "The OS loads the absent page before retrying.",
        13,
        "fault",
      ),
      ex(
        "Page boundary",
        "Offset zero starts the next virtual page.",
        16,
        "mapped",
      ),
    ],
  ),
  "bounded-buffer": spec(
    "Buffer capacity",
    1,
    4,
    2,
    [
      ["block", "Block producer when full"],
      ["drop", "Drop incoming item when full"],
    ],
    [
      ex("Backpressure", "A full buffer makes the producer wait.", 2, "block"),
      ex("Drop policy", "A full buffer rejects new work instead.", 2, "drop"),
      ex(
        "Larger buffer",
        "More producer operations fit before a consumer runs.",
        4,
        "block",
      ),
    ],
  ),
  "disk-scheduling": spec(
    "Initial head position",
    0,
    199,
    50,
    [
      ["fcfs", "First come, first served"],
      ["sstf", "Shortest seek time first"],
    ],
    [
      ex(
        "Arrival order",
        "Serve the fixed request queue as received.",
        50,
        "fcfs",
      ),
      ex(
        "Nearest request",
        "Choose the nearest remaining cylinder each time.",
        50,
        "sstf",
      ),
      ex(
        "Different starting head",
        "A new starting position changes the nearest-first order.",
        120,
        "sstf",
      ),
    ],
  ),
  "shortest-routing": spec(
    "B–D link cost",
    1,
    12,
    8,
    [
      ["online", "All links available"],
      ["offline", "B–C link unavailable"],
    ],
    [
      ex(
        "Choose the least-cost route",
        "Dijkstra relaxes links with nonnegative costs.",
        8,
        "online",
      ),
      ex(
        "Fail one link",
        "Recompute the route using available links.",
        8,
        "offline",
      ),
      ex(
        "Cheaper alternate path",
        "A changed cost can change the selected route.",
        1,
        "online",
      ),
    ],
  ),
  "sliding-window-network": spec(
    "Sender window (segments)",
    1,
    4,
    2,
    [
      ["reliable", "No segment loss"],
      ["loss", "Lose segment 2 once"],
    ],
    [
      ex(
        "Two segments in flight",
        "Cumulative ACKs advance the send window.",
        2,
        "reliable",
      ),
      ex(
        "Recover a gap",
        "Out-of-order data is buffered; ACK stops at the gap.",
        3,
        "loss",
      ),
      ex(
        "Stop and wait",
        "A window of one serializes progress.",
        1,
        "reliable",
      ),
    ],
  ),
  "congestion-control": spec(
    "Simulated path capacity (segments/round)",
    2,
    8,
    4,
    [
      ["aimd", "AIMD congestion avoidance"],
      ["fixed", "Fixed sending window"],
    ],
    [
      ex(
        "Probe and back off",
        "Increase by one; halve after a loss signal.",
        4,
        "aimd",
      ),
      ex(
        "Ignore congestion",
        "A fixed window keeps overshooting the path.",
        4,
        "fixed",
      ),
      ex(
        "More path capacity",
        "The loss threshold moves when capacity changes.",
        7,
        "aimd",
      ),
    ],
  ),
  encapsulation: spec(
    "Requested withdrawal",
    1,
    150,
    120,
    [
      ["guarded", "Validate through a method"],
      ["public", "Mutate a public field"],
    ],
    [
      ex(
        "Protect the invariant",
        "Reject a withdrawal larger than the balance.",
        120,
        "guarded",
      ),
      ex(
        "Bypass validation",
        "Direct mutation can create an invalid state.",
        120,
        "public",
      ),
      ex("Valid withdrawal", "A guarded operation can succeed.", 40, "guarded"),
    ],
  ),
  "adapter-pattern": spec(
    "Temperature in Celsius",
    0,
    100,
    25,
    [
      ["adapter", "Convert through adapter"],
      ["raw", "Pass raw number"],
    ],
    [
      ex(
        "Translate the contract",
        "The Fahrenheit client receives converted units.",
        25,
        "adapter",
      ),
      ex(
        "Contract mismatch",
        "The same number means different temperatures.",
        25,
        "raw",
      ),
      ex("Boiling-point conversion", "100°C becomes 212°F.", 100, "adapter"),
    ],
  ),
  "decorator-pattern": spec(
    "Base message bytes",
    10,
    200,
    100,
    [
      ["compress-encrypt", "Compress, then encrypt"],
      ["encrypt-compress", "Encrypt, then compress"],
    ],
    [
      ex(
        "Useful wrapper order",
        "Compressible data shrinks before encryption.",
        100,
        "compress-encrypt",
      ),
      ex(
        "Order changes behavior",
        "Encrypted bytes are not reduced by this compressor model.",
        100,
        "encrypt-compress",
      ),
      ex(
        "Small payload",
        "Fixed encryption overhead matters more for small messages.",
        20,
        "compress-encrypt",
      ),
    ],
  ),
};
function lesson(
  id: string,
  topic: TopicId,
  title: string,
  summary: string,
  idea: string,
  invariant: string,
  challenge: string,
  question: string,
  choices: string[],
  answer: number,
  explanation: string,
): Module {
  return {
    id,
    topic,
    title,
    kind: "deep",
    minutes: 18,
    summary,
    idea,
    invariant,
    challenge,
    quiz: { question, choices, answer, explanation },
  };
}
export const deeperModules: Module[] = [
  lesson(
    "load-balancing",
    "system-design",
    "Load balancing under uneven work",
    "Compare round robin with routing by queued service time.",
    "Equal request counts can hide very different amounts of work. A work-aware policy uses an estimate of queued service time.",
    "Each incoming job is assigned exactly once. This batch model does not run servers concurrently or model live latency.",
    "Compare both policies for six jobs. Explain why equal counts do not guarantee equal load.",
    "What does round robin balance directly?",
    ["Number of assignments", "Actual execution time", "Database capacity"],
    0,
    "It rotates assignments; it does not inspect each job’s cost.",
  ),
  lesson(
    "cache-invalidation",
    "system-design",
    "Cache freshness and invalidation",
    "Update storage and inspect what a reader sees before TTL expiry.",
    "A cache is a separate copy. Writes need a freshness policy: invalidate, refresh, or tolerate staleness until expiry.",
    "The durable value and cached value can differ. This single-threaded trace does not solve concurrent refill races.",
    "Run TTL-only and invalidation on the same update. Identify the stale read.",
    "Does a database write automatically update a separate cache?",
    ["Always", "No, a coherence policy is needed", "Only for integers"],
    1,
    "The cache must be invalidated, refreshed, or allowed to expire explicitly.",
  ),
  lesson(
    "replication-lag",
    "system-design",
    "Replication and read-your-writes",
    "Follow a committed write from a leader to a delayed replica.",
    "Asynchronous replication separates committing on the leader from applying on the replica. Choosing a read target changes freshness.",
    "The replica catches up after the configured delay. Reading the leader assumes the same leader stays available; failover is outside this model.",
    "Increase delay and compare leader versus replica reads immediately after a write.",
    "Why can a replica return an old value?",
    [
      "The write may not have been applied yet",
      "All replicas discard writes",
      "Indexes prevent replication",
    ],
    0,
    "A committed leader write can still be in transit to an asynchronous replica.",
  ),
  lesson(
    "rate-limiting",
    "system-design",
    "Token buckets and burst control",
    "Spend and refill tokens to accept or reject requests.",
    "A token bucket allows a bounded burst while replenishment limits sustained acceptance. Rejected requests must be handled by the caller.",
    "Tokens remain between zero and bucket capacity. Each accepted request consumes one token.",
    "Compare steady traffic with a burst, then increase the bucket capacity.",
    "What happens when a request arrives with zero tokens?",
    [
      "It is accepted for free",
      "It is rejected in this model",
      "Capacity doubles",
    ],
    1,
    "A request needs a token. This model rejects immediately rather than queueing.",
  ),
  lesson(
    "sql-aggregation",
    "databases",
    "GROUP BY and HAVING",
    "Accumulate per-customer totals and filter complete groups.",
    "GROUP BY collects rows with a shared key. Aggregate functions reduce each group, and HAVING filters the resulting group values.",
    "Every source row contributes once to its group. HAVING is evaluated after aggregation.",
    "Switch SUM to COUNT and change the threshold. Explain why their units differ.",
    "When is HAVING applied here?",
    [
      "Before source rows exist",
      "After grouping and aggregation",
      "Before every insert",
    ],
    1,
    "HAVING filters aggregated groups, while WHERE filters input rows.",
  ),
  lesson(
    "composite-index",
    "databases",
    "Composite index order",
    "Compare candidate ranges for two index column orders.",
    "An equality on the leading key followed by a range on the next key narrows a contiguous index interval. A leading range can leave later conditions as residual filters.",
    "Both index orders return the same logical result. Candidate counts are illustrative, not database query timings.",
    "Compare customer-first and amount-first indexes at the same threshold.",
    "Why can (customer, amount) help this query?",
    [
      "It groups one customer before scanning the amount range",
      "It removes all storage costs",
      "It changes matching rows",
    ],
    0,
    "Leading equality plus a following range can make the candidate interval smaller.",
  ),
  lesson(
    "transaction-isolation",
    "databases",
    "Isolation and repeated reads",
    "Read twice while a second transaction commits a change.",
    "Read committed may expose a newer committed version to each statement. Snapshot reads keep this transaction’s original version.",
    "Uncommitted writes are never read. This read-only model does not demonstrate write conflicts or guarantee serializability.",
    "Compare the two reads under each policy. Explain why a stable snapshot can differ from current storage.",
    "Which policy keeps both reads stable in this model?",
    ["Read committed always", "Snapshot reads", "Neither"],
    1,
    "Both reads use the version visible when the snapshot was taken.",
  ),
  lesson(
    "virtual-memory",
    "operating-systems",
    "Virtual addresses and page faults",
    "Translate a virtual page and offset through a page table.",
    "Page translation changes the page number into a physical frame number while preserving the offset. An absent page needs OS handling before access completes.",
    "Page size is four bytes in this toy model. Frame mappings are unique; address = frame × page size + offset.",
    "Try addresses 12, 13, and 16. Compare page boundaries and the absent-page case.",
    "Which part stays unchanged during translation?",
    ["The page number", "The offset within the page", "The whole address"],
    1,
    "The page table maps the page; the offset locates a byte within its frame.",
  ),
  lesson(
    "bounded-buffer",
    "operating-systems",
    "Producer–consumer backpressure",
    "Follow items through a bounded FIFO buffer.",
    "Capacity limits force a producer to wait or drop work. A consumer frees capacity by removing the oldest item.",
    "Buffer occupancy never exceeds capacity. Pending producers are FIFO and are admitted when a consumer frees space.",
    "Compare blocking and dropping with capacity one. Count delivered and rejected items.",
    "What does blocking do when the buffer is full?",
    [
      "Waits for capacity",
      "Overwrites the oldest item",
      "Makes capacity unlimited",
    ],
    0,
    "Backpressure delays the producer until space is available.",
  ),
  lesson(
    "disk-scheduling",
    "operating-systems",
    "Disk requests and seek distance",
    "Compare arrival order with shortest-seek-time-first.",
    "A rotating disk’s head movement depends on request order. Nearest-first can reduce movement in a batch but can starve distant requests in a continuing stream.",
    "All five requests are served once. Seek distance is cylinder movement, not a real latency prediction or an SSD model.",
    "Change the starting head and compare total distance. Explain the starvation trade-off.",
    "Which risk can SSTF introduce under continuous arrivals?",
    [
      "Starvation of distant requests",
      "Guaranteed zero movement",
      "Duplicate files",
    ],
    0,
    "A constant stream of nearby requests can delay distant ones.",
  ),
  lesson(
    "shortest-routing",
    "networks",
    "Routing with changing link costs",
    "Run Dijkstra’s algorithm over a small weighted network.",
    "A router can choose paths from a graph of link costs. Relaxing edges improves known distance estimates until the least-cost path is established.",
    "All link costs are nonnegative. This centralized snapshot omits routing protocol convergence, policy and packet loss.",
    "Fail B–C or lower B–D cost. Follow how the selected A-to-D route changes.",
    "Does the fewest-hop path always have the lowest cost?",
    ["Yes", "No, link weights also matter", "Only with four routers"],
    1,
    "A longer path can have lower total weight than a short expensive path.",
  ),
  lesson(
    "sliding-window-network",
    "networks",
    "Windows, gaps and cumulative ACKs",
    "Send several segments and recover a missing segment.",
    "A window permits more than one segment in flight. A cumulative ACK advances only past a contiguous prefix; later arrivals can wait in a receive buffer.",
    "Segments are numbered 1–6. This teaching protocol uses selective retry and idealized rounds; it is not a complete TCP implementation.",
    "Lose segment 2 with a window of three. Explain why ACK stops even when segment 3 arrived.",
    "What prevents a cumulative ACK from advancing?",
    [
      "A gap before the next expected segment",
      "Any buffered segment",
      "A large screen",
    ],
    0,
    "Later arrivals do not fill an earlier missing segment.",
  ),
  lesson(
    "congestion-control",
    "networks",
    "Congestion feedback and AIMD",
    "Probe a path’s capacity and reduce the sending window after loss.",
    "Additive increase explores available capacity slowly; multiplicative decrease backs off after congestion. The path capacity is a simplified loss threshold.",
    "AIMD uses +1 after success and floor(window/2), minimum one, after loss. Slow start, RTT variation and real TCP variants are omitted.",
    "Compare adaptive and fixed windows at different capacities. Count overshoot rounds.",
    "Why reduce the window after congestion?",
    [
      "To reduce offered load",
      "To erase delivered data",
      "To disable acknowledgments",
    ],
    0,
    "Reducing in-flight work helps relieve the overloaded path.",
  ),
  lesson(
    "encapsulation",
    "oop",
    "Encapsulation protects an invariant",
    "Compare validated withdrawal with direct balance mutation.",
    "An object can expose operations that preserve its rules. Hiding state supports those rules only when every mutation path validates them.",
    "The guarded account never becomes negative. This single-threaded example excludes concurrent withdrawals.",
    "Try withdrawing 120 and then 40 from a balance of 100.",
    "What is the purpose of the guarded method?",
    [
      "Preserve a valid state",
      "Make every operation succeed",
      "Hide error handling forever",
    ],
    0,
    "The method validates a proposed change before applying it.",
  ),
  lesson(
    "adapter-pattern",
    "oop",
    "Adapter: translate a contract",
    "Bridge a Celsius source to a Fahrenheit consumer.",
    "An adapter translates an existing interface into the one a client expects. The conversion must preserve meaning, not just match types.",
    "The adapter follows F = C × 9/5 + 32. Passing the original number violates the client’s unit contract.",
    "Compare the raw and adapted values at 0°C and 100°C.",
    "Why is forwarding the raw number wrong?",
    [
      "The client expects a different unit",
      "Numbers cannot cross interfaces",
      "Adapters require inheritance",
    ],
    0,
    "The caller expects Fahrenheit; a Celsius value must be converted.",
  ),
  lesson(
    "decorator-pattern",
    "oop",
    "Decorator: order changes behavior",
    "Wrap a message writer with compression and encryption steps.",
    "Decorators compose behavior through a common contract. Wrapper order can change both semantics and output.",
    "Compression halves plaintext size rounded up; encryption adds 16 bytes; encrypted data is incompressible in this toy size model. No real encryption occurs.",
    "Compare both wrapper orders for small and large messages.",
    "Does decorator order matter here?",
    [
      "No",
      "Yes, compression after encryption cannot shrink the payload",
      "Only for empty code",
    ],
    1,
    "The compression wrapper can reduce plaintext but not the encrypted representation in this model.",
  ),
];
