export type CourseUnit = {
  prerequisites: string[];
  concept: string;
  worked: { prompt: string; steps: string[]; answer: string };
  comparison: { baseline: string; improved: string; tradeoff: string };
  misconception: string;
  transfer: { prompt: string; hint: string; solution: string };
  rubric: string[];
};
const u = (
  pre: string,
  concept: string,
  prompt: string,
  steps: string,
  answer: string,
  baseline: string,
  improved: string,
  tradeoff: string,
  misconception: string,
  transfer: string,
  hint: string,
  solution: string,
  rubric: string,
): CourseUnit => ({
  prerequisites: pre.split("|"),
  concept,
  worked: { prompt, steps: steps.split("|"), answer },
  comparison: { baseline, improved, tradeoff },
  misconception,
  transfer: { prompt: transfer, hint, solution },
  rubric: rubric.split("|"),
});
export const csCourseContent: Record<string, CourseUnit> = {
  "request-journey": u(
    "Functions and request/response|A queue holds waiting work",
    "A service is a chain of responsibilities. A client asks for work; an application checks and performs it; storage preserves the result. Throughput depends on the slowest required shared stage, while latency includes processing and waiting along the path. Start with a route that works before adding replicas.",
    "A gateway handles 1,000 requests/s, an application 150, and a database 80. What limits 120 incoming requests/s?",
    "Identify which components every request must visit.|The required database can complete at most 80 requests/s in this simplified capacity model.|Adding a second application gives 300 application requests/s, but the same database still limits the route.",
    "At most 80 requests/s complete; up to 40 requests/s exceed the bottleneck capacity.",
    "Send every request through one application and one database.",
    "Replicate the stage that measurements identify as the bottleneck.",
    "Replicas introduce routing, shared state and failure-management costs.",
    "Adding servers anywhere does not automatically multiply end-to-end capacity.",
    "The database is fast enough for 200 requests/s, but authentication supports 60. Where should you investigate?",
    "List every required stage, including dependencies.",
    "Authentication limits the route to 60 requests/s. Inspect its work and failures before scaling an unrelated component.",
    "Trace one complete request|Identify the required bottleneck|Explain capacity-model assumptions",
  ),
  "url-shortener": u(
    "Request journey|Keys, lookups and unique constraints",
    "Separate creation from redirection. Creation allocates a unique short key and stores a durable mapping. Redirection retrieves that mapping and returns a redirect. A cache speeds repeated reads but cannot replace durable storage or authorization rules.",
    "Design a short-link service with 1 million creations and 100 million redirects per day.",
    "Clarify expiration, custom aliases and whether duplicate URLs may receive distinct keys.|Define create(url) and redirect(key), and a mapping with a unique key constraint.|The read/write ratio is 100:1. Cache popular lookups; keep the database authoritative.|Handle a missing or expired key explicitly. Retry allocation after a unique-key collision.",
    "A read-heavy service with durable mappings and cached redirects. Average redirects are about 1,157/s; peaks require a separate estimate.",
    "Read storage on every redirect.",
    "Cache hot mappings; partition storage only when measured capacity requires it.",
    "Caches may hold expired mappings unless invalidation and expiry are designed.",
    "A hash of a URL is not a guarantee of uniqueness.",
    "Two clients concurrently request the same custom alias. What decides the winner?",
    "Enforce the rule at the shared storage boundary.",
    "Use a database uniqueness constraint or an equivalent atomic reservation. One request succeeds; the other receives an alias-conflict response. A prior read alone is unsafe.",
    "Define creation and redirect contracts|Separate average from peak traffic|Handle collisions and expiration",
  ),
  "chat-service": u(
    "Queues|Persistent records|Client connections",
    "Message acceptance, persistence, delivery and reading are different events. An acknowledgment must say which event it confirms. Offline users need stored messages or durable delivery state. A conversation sequence helps clients order messages despite reconnection and retries.",
    "A sender retries a message after losing the acceptance acknowledgment. How do you avoid displaying two copies?",
    "Give the client request a stable message identifier.|Persist the message and its identifier atomically or enforce uniqueness.|A retry with the same identifier returns the previous acceptance result.|Recipients deduplicate delivery using the message identifier and reconcile conversation order.",
    "One accepted logical message can have multiple transport attempts.",
    "Treat every retry as a new message and push directly to connected users.",
    "Persist a stable message identity and use idempotent acceptance and delivery handling.",
    "Deduplication needs a retention policy; ordering across different conversations is a separate problem.",
    "Receiving a transport acknowledgment does not mean a recipient has read the message.",
    "A user disconnects after receiving messages 10 and 12, but not 11. What should reconnect do?",
    "Use sequence gaps rather than assuming the largest number is complete.",
    "Request the missing range or replay from the last contiguous confirmed sequence. Preserve deduplication when 12 is delivered again.",
    "Define acknowledgment semantics|Handle retries idempotently|Explain offline recovery and ordering",
  ),
  notifications: u(
    "Queues and workers|Retries|Idempotency",
    "Asynchronous delivery decouples acceptance from provider availability. The queue retains work while workers attempt delivery. Bounded retries with backoff prevent a broken provider from consuming all capacity. A dead-letter path preserves failures for diagnosis and replay.",
    "A provider is unavailable for 60 seconds while 50 jobs/s arrive. How much work accumulates if no jobs are processed?",
    "Use arrivals minus completions to reason about backlog.|Zero completions for 60 seconds leaves 3,000 jobs queued.|After recovery, processing at 100 jobs/s while arrivals remain 50 drains a net 50 jobs/s.|The initial backlog takes another 60 seconds to drain if those rates stay constant.",
    "3,000 queued jobs; 60 seconds of recovery at the stated steady rates.",
    "Call the provider synchronously on every user request.",
    "Accept durably, enqueue, and let workers retry independently.",
    "Users get eventual delivery rather than immediate confirmation; duplicates and expiry need policies.",
    "A queue absorbs bursts but cannot make an insufficient long-term processing rate stable.",
    "The provider receives a job but the worker crashes before recording success. What is the risk?",
    "Distinguish a failed acknowledgment from failed delivery.",
    "The job may be retried and delivered twice. Use a stable delivery key when supported, record outcomes, and state the remaining at-least-once semantics.",
    "Calculate backlog and drain rate|Set retry and dead-letter policies|State duplicate-delivery guarantees",
  ),
  "news-feed": u(
    "Associations between users|Queues|Cache freshness",
    "Building a feed means choosing when to combine followed users’ posts. Write-time fan-out prepares inboxes when a post arrives; read-time assembly combines posts when the reader asks. The choice depends on follower distribution and how often readers return.",
    "A user with 1 million followers posts once. Compare eager fan-out with read-time assembly.",
    "Eager fan-out schedules up to 1 million inbox updates for one post.|Read-time assembly avoids those immediate writes but does extra work when followers request feeds.|A hybrid can eagerly distribute ordinary accounts and fetch high-fan-out accounts at read time.|Define ranking, pagination and deletion behavior separately from the distribution strategy.",
    "A hybrid can reduce write spikes while preserving quick reads for ordinary accounts.",
    "Fetch and merge every followed account on every request.",
    "Materialize common feed results and use a hybrid for unusually large fan-out.",
    "Prepared feeds cost storage and freshness coordination; read-time work costs request latency.",
    "One feed strategy is not best for every follower distribution.",
    "A cached feed includes a deleted post. Where must correctness be enforced?",
    "A distribution cache is not an authorization authority.",
    "Apply visibility and deletion rules when preparing or serving entries; invalidate affected data where feasible. Never rely solely on a stale cached list to authorize access.",
    "Compare read-time and write-time work|Recognize skewed fan-out|Address freshness and visibility",
  ),
  "load-balancing": u(
    "Queues|Service time versus request count",
    "Round robin distributes counts, not costs. Least queued work uses estimated remaining service demand. When jobs differ in cost, equally sized queues can have very different completion times. Health checks and connection affinity are additional choices beyond the scheduling rule.",
    "Three servers have queued work [8,2,5]. A new job costs 4 units. Which destination does least-work choose?",
    "Compare queued work before adding the new job.|The second server has the smallest total, 2.|Assign the job there, producing [8,6,5].",
    "Server 2; its queued work becomes 6 units.",
    "Rotate across servers without considering outstanding work.",
    "Choose a healthy server using queued-work or connection estimates.",
    "Measurements can be delayed; routing decisions and stickiness may conflict.",
    "Equal request counts do not imply equal server load.",
    "The least-work server is unhealthy but reports zero work. Should it receive the request?",
    "Eligibility comes before optimization.",
    "Exclude unhealthy servers before applying the load-selection rule. Recheck health and define how in-flight requests fail or retry.",
    "Separate counts from work|Apply health eligibility|Explain stale measurements",
  ),
  "cache-invalidation": u(
    "Read/write operations|Authoritative storage",
    "A cache stores a copy, so every write raises a freshness question. TTL limits how long a copy remains eligible but does not immediately propagate writes. Explicit invalidation removes an old copy; cache-aside then refills it on a later miss. Concurrent refill can still race with a writer.",
    "Storage and cache both contain 10. Storage changes to 20 before the TTL expires. What does each policy return?",
    "With TTL-only reuse, a valid cached copy can still return 10.|With successful invalidate-on-write, the next cache-aside read misses.|That read obtains 20 from storage and refills the cache.",
    "TTL-only can return 10; successful invalidation followed by refill returns 20.",
    "Cache entries until their TTL expires.",
    "Invalidate affected keys on committed writes and define refill ordering.",
    "Invalidation adds coordination and failure cases; stronger guarantees may require versions or transactions.",
    "TTL is a staleness policy, not a read-your-writes guarantee.",
    "A reader fetches 10, then a writer commits 20 and invalidates, then the reader caches 10. What failed?",
    "Order the read, commit, invalidation and refill events.",
    "A stale refill happened after invalidation. Use version checks, a coordinated update policy, or an explicit bounded-staleness guarantee rather than assuming deletion alone is enough.",
    "Distinguish copies from authority|Describe TTL and invalidation|Recognize stale-refill races",
  ),
  "replication-lag": u(
    "Leader and replica roles|Committed writes",
    "A replica can be healthy and still behind the leader. Read-your-writes is a session guarantee: after a successful write, that client should not observe older state. Leader reads, a version barrier or session routing can supply this guarantee under stated availability assumptions.",
    "A leader changes a balance from 100 to 140. The replica still has 100. What can a read observe?",
    "Record the write version at the leader.|A replica read before applying the update may return 100.|A leader read after the committed write can return 140.|After replication catches up, the replica can also return 140.",
    "The observation depends on the read destination and replication progress.",
    "Distribute all reads to any replica immediately.",
    "Route the writing session to a sufficiently current replica or the leader.",
    "Freshness requirements can increase latency or reduce availability during failure.",
    "Replication is not instantaneous just because replicas are online.",
    "The leader fails immediately after acknowledging a write. What must a durability claim specify?",
    "Ask which machines stored the acknowledged write.",
    "Specify the acknowledgment and replication rule, failure assumptions and election behavior. Asynchronous replication can lose a recently acknowledged write on failover; the simple lag model alone proves no durability guarantee.",
    "State the session guarantee|Separate freshness from durability|Explain failover assumptions",
  ),
  "rate-limiting": u(
    "Counters|Elapsed time|Request admission",
    "A token bucket separates burst allowance from sustained rate. The bucket holds at most B tokens and refills at r tokens per time unit. A request spends tokens only if enough are available. Distributed enforcement must define the key, clock and atomicity of updates.",
    "Capacity is 5, refill is 2 tokens/s, and the bucket starts full. Eight requests arrive together. What happens?",
    "At the same instant, only the initial 5 tokens are available.|Admit 5 requests and reject or defer 3 according to the contract.|After one idle second, 2 tokens are available.|A cap prevents saving more than 5 tokens during a long idle period.",
    "Five immediate admissions; two more tokens after one idle second.",
    "Count requests in fixed windows, allowing boundary bursts.",
    "Track bounded tokens and refill continuously or in defined discrete ticks.",
    "Per-client state costs memory; shared enforcement needs atomic operations and a failure policy.",
    "The bucket capacity is not the sustained refill rate.",
    "Two gateways each grant a user a full 5-token bucket. What happens to a global 5-request burst rule?",
    "Consider whether the state is shared or per gateway.",
    "The user can receive 10 immediate admissions. Use shared atomic state, partition ownership by key, or describe the quota as approximate and bound its error.",
    "Explain burst and sustained rate|Choose a quota key|Address atomic distributed updates",
  ),
  "sql-joins": u(
    "Tables, rows and keys|NULL means unknown or absent",
    "A join associates rows using a predicate. One-to-many matches multiply rows, so output count is not customer count. LEFT JOIN preserves unmatched left rows with NULL right-side values. A WHERE predicate on the right table can remove those preserved rows.",
    "Customers A and B exist. A has orders 30 and 50; B has none. Compare INNER and LEFT joins.",
    "INNER JOIN emits two rows for A, one per matching order.|LEFT JOIN emits those two rows plus B with a NULL order.|A later WHERE order.amount >= 40 keeps only A’s 50 row; the NULL comparison is not true.",
    "INNER: 2 rows. LEFT: 3 rows. LEFT followed by the stated WHERE: 1 row.",
    "Combine tables by matching every pair and filtering later.",
    "State the join type and put predicates where their intended semantics are clear.",
    "Physical join algorithms affect work; they must preserve the same logical result.",
    "LEFT JOIN does not guarantee preserved rows survive later WHERE filtering.",
    "How can you keep B while only matching A’s orders of at least 40?",
    "Place the qualifying condition inside the join predicate.",
    "Use LEFT JOIN ... ON customer.id = order.customer_id AND order.amount >= 40. B remains unmatched; A’s 50 order matches.",
    "Track row multiplicity|Explain NULL filtering|Separate logical result from execution cost",
  ),
  "sql-aggregation": u(
    "Joins and filtering|Groups and aggregate functions",
    "WHERE selects input rows; GROUP BY partitions the remaining rows; aggregate functions reduce each group; HAVING selects complete groups. Counting joined rows differs from counting non-NULL values. The order of these operations changes the question being answered.",
    "A has orders 30 and 50; B has 90. Keep customers with total order amount at least 80.",
    "Group by customer rather than by order.|A’s sum is 80; B’s is 90.|HAVING SUM(amount) >= 80 preserves both groups.",
    "A → 80 and B → 90.",
    "Filter individual amounts >= 80, which answers a different question.",
    "Aggregate all eligible rows first and filter group totals with HAVING.",
    "Grouping requires memory or external work; indexes and plans can alter cost.",
    "WHERE amount >= 80 is not equivalent to HAVING SUM(amount) >= 80.",
    "For a LEFT JOIN, why can COUNT(*) be 1 for a customer with no orders?",
    "The preserved unmatched row still exists.",
    "COUNT(*) counts that output row. COUNT(order.id) ignores the NULL order id and returns zero when no real order matched.",
    "Order WHERE, GROUP BY and HAVING|Choose the correct counted expression|Predict totals before filtering",
  ),
  "database-index": u(
    "Sorted order|Lookup predicates",
    "An index narrows the records a query may need to inspect. An ordered structure supports range predicates; a hash structure supports its own lookup contract. Real database indexes operate on pages and may require additional row fetches. Index maintenance adds write work.",
    "Search ordered keys [3,7,11,15,19,23,27] for 23 using midpoint comparisons.",
    "Compare index 3, value 15: discard indices 0 through 3.|Compare index 5, value 23: the key matches.|A left-to-right scan would inspect 6 keys for this input.",
    "Two midpoint comparisons versus six scan inspections in this array example.",
    "Scan every key until a match or the end.",
    "Use an index suited to the predicate and data distribution.",
    "An index costs storage and updates; low-selectivity queries may favor scans.",
    "The array model illustrates search reduction; it is not an exact B-tree page-I/O model.",
    "A query needs almost every row. Must an index be faster?",
    "Count both index reads and any table-row fetches.",
    "No. A scan can avoid many random row fetches and exploit sequential access. Compare actual plans and selectivity.",
    "Explain selectivity|Account for writes and row fetches|Distinguish teaching comparisons from page I/O",
  ),
  "composite-index": u(
    "Ordered indexes|Equality and range predicates",
    "A composite index orders tuples lexicographically. With (customer, amount), a fixed customer forms a contiguous run ordered by amount. With (amount, customer), an amount range can span many customers. The useful prefix depends on the actual predicate, ordering and storage system.",
    "For orders (A,20), (A,80), (B,30), (B,90), query A with amount >= 50.",
    "With (customer, amount), locate A’s run first, then the amount range within it.|With (amount, customer), qualifying amounts include both A and B, so the customer predicate still removes candidates.|Both indexes must return the same logical row: (A,80).",
    "Same answer; a different candidate region and potential amount of work.",
    "Choose index column order without considering the query.",
    "Start with common equality constraints and then the relevant range/order requirements.",
    "More indexes add write cost; a different workload can prefer a different order.",
    "A composite index is not automatically equally useful for every subset of its columns.",
    "If all queries filter only amount, which of these two orders is more directly useful?",
    "Ask which first column supplies an ordered search prefix.",
    "(amount, customer) directly organizes the amount range. Some engines have additional access techniques, so verify the actual plan rather than declaring the other order unusable.",
    "Locate a lexicographic range|Preserve query results|Qualify claims with real query plans",
  ),
  transactions: u(
    "Committed versus working state|Failure between operations",
    "Atomicity groups operations into one committed outcome. A transfer must not expose a permanently half-applied debit and credit. Isolation determines what concurrent transactions observe; durability concerns persistence after acknowledgment. These are distinct guarantees.",
    "Accounts hold 100 and 40. Transfer 30, then inject failure after the debit.",
    "A successful working state would become 70 and 70.|The failure occurs before the transaction commits.|Roll back the working change so committed balances remain 100 and 40.",
    "Committed total remains 140; the failed transfer changes neither committed balance.",
    "Commit debit and credit independently.",
    "Commit both changes together or roll both back.",
    "Transactions can hold locks, abort or require retry; side effects outside the database need separate coordination.",
    "Atomicity alone does not prevent every concurrent anomaly or make an external email transactional.",
    "A committed transfer is retried after the client loses its response. How can the service avoid a second transfer?",
    "Give the logical operation a durable identity.",
    "Store a unique transfer id and its outcome in the same transaction as the balances. Return that outcome when the same id is retried.",
    "Separate working and committed state|Preserve the balance invariant|Handle ambiguous retries",
  ),
  normalization: u(
    "Keys and relationships|Functional dependencies",
    "Normalization organizes facts around their dependencies. Repeating one course’s instructor in every enrollment creates multiple places to update the same fact. A separate course record gives that fact one owner; joins reconstruct the view when needed.",
    "Three enrollment rows repeat that CS101 is taught by Rao. One row changes to Park. What is the anomaly?",
    "The rows now disagree about one course’s instructor.|Store courseId → instructor once in a Courses table.|Keep studentId and courseId in Enrollments and join to read the instructor.",
    "One course-row update replaces three potentially inconsistent copies.",
    "Repeat course facts in each enrollment.",
    "Separate entities and reference them with keys and constraints.",
    "Normalized reads may join more tables; intentional denormalization needs an update policy.",
    "Removing duplicate-looking values without examining dependencies is not normalization.",
    "Two courses share the same instructor name. Should they be merged?",
    "An equal value does not establish entity identity.",
    "No. Course identifiers determine course facts. Shared names do not make two courses the same entity; a separate instructor entity is appropriate only if its own identity and facts are needed.",
    "Identify the functional dependency|Explain update anomalies|Choose keys before decomposing",
  ),
  "transaction-isolation": u(
    "Transactions|Committed writes|Interleaved operations",
    "Isolation controls which versions a transaction can see and which execution histories are allowed. Repeated reads can differ under read committed when another transaction commits between them. A stable snapshot avoids that particular observation, but is not automatically serializable.",
    "A reads 100. B adds 20 and commits. A reads the same item again.",
    "Under the lab’s read-committed behavior, the second read sees the new committed 120.|Under the lab’s stable-snapshot behavior, A continues to see 100.|Neither observation alone proves how writes, conflicts or all database engines behave.",
    "Second read: 120 with this read-committed model; 100 with this snapshot model.",
    "Assume a transaction always sees a fixed database view.",
    "Choose an isolation contract and reason about the permitted interleaving.",
    "Stronger isolation can increase waiting, conflict detection and retries.",
    "A stable read snapshot is not a proof that write skew or every other anomaly is prevented.",
    "Two doctors each see the other on duty, then each goes off duty on a different row. Why can a stable snapshot still be insufficient?",
    "Each transaction can preserve its own read view while violating a shared predicate.",
    "Both can commit disjoint writes based on old snapshots, leaving nobody on duty. Use an isolation or locking strategy that protects the shared rule and handle aborts.",
    "Write the interleaving|Identify the protected invariant|Distinguish repeatable reads from serializability",
  ),
  "cpu-scheduling": u(
    "Queues|CPU burst length|Waiting and turnaround time",
    "A scheduler chooses which ready process runs next. FCFS preserves arrival order; nonpreemptive SJF runs the shortest known burst; round robin rotates unfinished jobs after a quantum. Evaluate the policy using explicit workload and cost assumptions.",
    "All jobs arrive at 0 with bursts [5,3,1]. Compute FCFS waiting times.",
    "P1 starts at 0 and finishes at 5.|P2 starts at 5 and finishes at 8.|P3 starts at 8 and finishes at 9.|Waiting times are [0,5,8]; average waiting is 13/3.",
    "Average waiting is about 4.33 time units; completion times are [5,8,9].",
    "Preserve arrival order without considering responsiveness.",
    "Compare SJF for this known workload and round robin for turn-taking.",
    "Short quanta improve turn-taking but real systems pay context-switch costs; SJF needs burst estimates and fairness handling.",
    "Waiting time is not the same as turnaround time.",
    "For the same jobs, what is SJF’s average waiting time?",
    "Run the 1-unit job, then the 3-unit job, then the 5-unit job.",
    "In execution order P3, P2, P1, waits are 0, 1 and 4. The average is 5/3 ≈ 1.67, under these all-at-zero, no-overhead assumptions.",
    "Compute waits and completions|State arrival and overhead assumptions|Explain responsiveness and starvation",
  ),
  "page-replacement": u(
    "Virtual pages and physical frames|Cache hits and misses",
    "When all frames are occupied, a miss requires choosing a page to evict. FIFO tracks insertion age; LRU tracks recent use. The future reference sequence determines which policy helps. A hit may update recency without changing the pages present.",
    "Use two frames and references [1,2,1,3,2]. Compare FIFO and LRU.",
    "Both load 1 and 2, then hit on 1.|FIFO evicts 1 when 3 arrives, because 1 was loaded first. The final 2 is a hit.|LRU evicts 2 when 3 arrives, because 1 was just used. The final 2 faults.",
    "FIFO: 3 faults. LRU: 4 faults for this particular sequence.",
    "Evict the page that arrived first.",
    "Use recency or another policy justified by workload and tracking cost.",
    "Exact recency bookkeeping costs work; real systems often approximate it.",
    "LRU does not beat FIFO on every individual reference sequence.",
    "Does accessing page 1 make it newest under FIFO?",
    "Track insertion order separately from usage order.",
    "No. A FIFO hit leaves its insertion age unchanged. Under LRU, the hit refreshes its recency.",
    "Track policy metadata|Count faults accurately|Avoid universal policy-performance claims",
  ),
  "virtual-memory": u(
    "Integer division and remainder|Page tables|Physical frames",
    "Address translation splits a virtual address into a page number and offset. The page table supplies the physical frame, while the offset stays unchanged. A missing or prohibited mapping triggers a fault rather than an invented physical address.",
    "Page size is 16 bytes. Virtual address 53 belongs to a page mapped to physical frame 9. Find the physical address.",
    "Compute page = floor(53/16) = 3.|Compute offset = 53 mod 16 = 5.|Preserve offset 5 in frame 9: 9×16 + 5.",
    "Physical address 149, assuming page 3 is present and access is permitted.",
    "Treat a virtual address as a direct physical address.",
    "Look up the page mapping and preserve the offset.",
    "Translation requires metadata and may miss in a TLB; permissions and fault handling are additional steps.",
    "A page fault is not necessarily an invalid program access; a valid page may need loading.",
    "What happens if page 3 is absent?",
    "Do not substitute an arbitrary frame number.",
    "The CPU traps to fault handling. If the address is valid, the OS can arrange a page load and mapping before retrying. Otherwise it rejects the access.",
    "Split page and offset|Check presence and permissions|Explain the fault path",
  ),
  synchronization: u(
    "Threads and interleaving|Read-modify-write|Mutual exclusion",
    "An increment usually involves reading, calculating and writing. Two threads can lose an update if these actions interleave without protection. A lock makes the protected critical section mutually exclusive; an atomic operation can provide the needed indivisible update directly.",
    "A and B both increment a counter initially 0. Show an unsafe outcome.",
    "A reads 0.|B reads 0.|A writes 1.|B writes 1, overwriting the effect of A’s increment.",
    "Final counter 1 despite two increments; a protected implementation should reach 2.",
    "Read and write shared state without coordination.",
    "Protect the complete update with a lock or a suitable atomic primitive.",
    "Locks can block, contend or deadlock; atomic primitives require a precise memory and operation contract.",
    "Locking only the write leaves the earlier read-modify decision unprotected.",
    "Would separate locks for A and B protect the shared counter?",
    "Mutual exclusion requires a shared coordination mechanism.",
    "No. Each thread can enter its own unrelated lock simultaneously. They need the same lock for that counter or a single suitable atomic increment operation.",
    "Enumerate an interleaving|Protect the whole invariant|Use the same synchronization boundary",
  ),
  "bounded-buffer": u(
    "Queues|Producer and consumer roles|Waiting conditions",
    "A bounded queue has both data and space conditions. A producer may enqueue only when capacity is available; a consumer may dequeue only when an item exists. A waiting operation must recheck its condition after wakeup because another participant may consume the opportunity first.",
    "Capacity is 2. Produce A, produce B, attempt C, consume one item, then retry C.",
    "After A and B, the buffer is full.|A blocking producer waits for space; a rejection policy refuses C instead.|A consumer removes A, creating one slot.|The blocked producer can recheck and enqueue C, giving [B,C].",
    "Blocking policy can eventually produce [B,C]; a rejected C needs an explicit caller retry.",
    "Grow the queue without bound during a producer burst.",
    "Bound the queue and specify block, reject or drop semantics.",
    "Backpressure controls memory but can move waiting upstream; fairness and shutdown need design.",
    "A condition-variable wakeup does not guarantee the condition remains true.",
    "Why check for space in a while loop instead of just one if?",
    "Another producer can acquire the lock before the awakened producer.",
    "After reacquiring the lock, recheck capacity and wait again if necessary. This also handles permitted spurious wakeups.",
    "Track capacity and occupancy|Separate blocking from rejection|Recheck conditions under the lock",
  ),
  deadlocks: u(
    "Resource ownership|Mutual exclusion|Wait-for relationships",
    "A deadlock is a cycle of dependencies with no participant able to release what the next needs. Prevention changes a necessary condition, such as circular waiting. Detection finds a cycle and recovery breaks it. Waiting alone is not proof of deadlock.",
    "A holds lock X and waits for Y. B holds Y and waits for X. How can a global lock order prevent this?",
    "The wait-for graph contains A → B → A.|Require every thread to acquire X before Y.|B must not acquire Y first and then request X.|Consistent acquisition order removes this two-lock circular wait.",
    "A shared X-before-Y rule prevents this particular cycle.",
    "Allow each caller to acquire needed locks in any order.",
    "Apply a consistent resource order or use detection and a defined recovery policy.",
    "Ordering can constrain concurrency; recovery may need rollback and can repeatedly disadvantage a victim.",
    "A timeout suggests excessive waiting but does not by itself prove or safely resolve deadlock.",
    "A needs X then Y and another thread needs Y then Z. What must the ordering rule cover?",
    "Use one order over all shared lock identities.",
    "Define a global order such as X < Y < Z and require every multi-lock acquisition to respect it. A rule covering only one pair can leave larger cycles.",
    "Draw the dependency cycle|State the global order|Explain prevention versus recovery",
  ),
  "disk-scheduling": u(
    "Request queues|Absolute distance|Mechanical seek model",
    "A disk scheduling policy reorders pending requests to control head movement and delay. FCFS preserves arrivals; SSTF chooses the nearest pending request. The teaching model counts cylinder distance and omits rotation, transfer and device-specific behavior.",
    "Head starts at 50 and requests are [10,55,20]. Compare FCFS with SSTF.",
    "FCFS travels |50−10| + |10−55| + |55−20| = 40+45+35 = 120.|SSTF visits 55 first, then 20, then 10.|Its travel is 5+35+10 = 50.",
    "FCFS distance 120; SSTF distance 50 for this batch.",
    "Serve requests strictly in arrival order.",
    "Choose a nearby request or a directional policy when its delay trade-offs fit.",
    "SSTF can starve distant requests under continuous nearby arrivals; fairness must be addressed.",
    "Cylinder distance is not a complete latency model and is not an SSD seek metric.",
    "Nearby requests arrive forever. What can happen to a far request under SSTF?",
    "The far request may never become the nearest.",
    "It can suffer unbounded waiting. Consider aging, bounded waiting or a sweeping policy and state how fairness is measured.",
    "Calculate route distance|Name omitted device costs|Address starvation",
  ),
  "dns-lookup": u(
    "Names and addresses|Cache expiry|Request/response",
    "DNS resolution follows delegated naming authority. A recursive resolver may use cached answers or query the hierarchy. TTL controls cache reuse duration. DNS resolves names; it does not establish a secure HTTP connection or prove the content behind an address is trustworthy.",
    "A resolver cached an address with TTL 60 seconds at t=0. Can it reuse that entry at t=30 and t=70?",
    "At t=30, 30 seconds of the TTL remain, so reuse is permitted under this simplified model.|At t=70, the TTL has expired and a fresh resolution is needed.|Changing authoritative data at t=10 does not immediately erase other resolvers’ cached copies.",
    "Reuse at t=30; refresh at t=70.",
    "Resolve every query through the hierarchy.",
    "Reuse cached answers within their validity and honor delegation rules.",
    "Caching reduces latency and query load but permits bounded stale answers and needs negative-caching behavior.",
    "A DNS cache hit does not skip HTTP authorization, TLS verification or application-level checks.",
    "Why might different clients temporarily resolve different addresses after a change?",
    "Their resolvers can have different cache ages.",
    "Independent caches expire at different times, and authoritative rollout can also differ. Investigate TTLs, resolver behavior and delegation rather than assuming one universal instant update.",
    "Trace authority and recursion|Reason about TTL age|Separate DNS from transport and application checks",
  ),
  "https-journey": u(
    "DNS resolution|TCP connections|Encryption and certificates",
    "Loading an HTTPS resource involves multiple layers: locating an endpoint, establishing transport, negotiating TLS, verifying the peer and exchanging application data. Connection reuse avoids repeating some setup, but only when the existing connection and protocol allow it.",
    "A browser has no cached DNS answer or existing connection. Name the main stages of a conventional HTTPS request over TCP.",
    "Resolve the hostname to an endpoint address.|Establish a TCP connection.|Negotiate TLS and validate the server identity under the client’s trust rules.|Send the HTTP request over the protected connection and process the response.",
    "DNS → TCP → TLS verification/negotiation → HTTP exchange, with failures handled at each stage.",
    "Create a new connection for every resource.",
    "Reuse eligible connections and cache appropriate results.",
    "Reuse reduces setup work but requires lifecycle management; HTTP/3 uses QUIC rather than this TCP path.",
    "HTTPS is not the claim that the application’s data or authorization decisions are correct.",
    "DNS succeeded, but certificate verification fails. Has the page loaded securely?",
    "Endpoint discovery and peer authentication are separate steps.",
    "No. The authenticated TLS stage has failed. Diagnose the identity or trust failure; do not treat successful resolution as proof of a secure session.",
    "Distinguish the layers|State connection assumptions|Identify the failed stage",
  ),
  "tcp-retries": u(
    "Sequence numbers|Acknowledgments|Timeouts",
    "A sender cannot equate silence with failed delivery. Data or its acknowledgment may have been lost. Sequence information lets the receiver recognize repeats, and acknowledgments tell the sender what has been received according to the protocol’s convention.",
    "A sender transmits segment 2. The receiver accepts it, but its acknowledgment is lost. What should a retry do?",
    "The sender times out because it cannot confirm the delivery.|It retransmits the same logical segment identity.|The receiver recognizes already received data instead of delivering a duplicate to the application.|It acknowledges again.",
    "Transport may repeat data; the application byte stream should not repeat those bytes.",
    "Treat a timeout as proof that the receiver never got the data.",
    "Retransmit with stable sequence information and deduplicate at the receiving protocol layer.",
    "Timeout selection trades delay against unnecessary retries; congestion and receiver capacity also constrain sending.",
    "The lab uses simplified segment identities; real TCP sequence numbers count bytes.",
    "Why should a retry keep its old sequence identity?",
    "The receiver needs to recognize the repeated logical data.",
    "A new identity would make the retry appear to contain new data and could duplicate application output. Preserve the byte positions or the teaching model’s segment identity.",
    "Distinguish data loss from ACK loss|Preserve logical identity|Qualify segment-versus-byte numbering",
  ),
  "sliding-window-network": u(
    "Sequence and ACK conventions|Bounded in-flight work",
    "A sending window permits several unacknowledged units in flight. A cumulative acknowledgment advances only over a contiguous received prefix. Data beyond a gap can be buffered without making the gap disappear. Flow control and congestion control impose distinct limits.",
    "Segments 1, 3 and 4 arrive, but 2 is missing. What is the next missing sequence under a next-expected convention?",
    "The receiver can confirm the contiguous prefix ending at 1.|Segments 3 and 4 do not fill the gap at 2.|The next-expected acknowledgment remains 2 until segment 2 arrives.|After 2 arrives, the contiguous prefix can include 1 through 4 and the next expected number becomes 5.",
    "Next expected: 2 before recovery, then 5 after filling the gap.",
    "Send one unit and wait for an acknowledgment each time.",
    "Use a bounded window and track gaps and contiguous progress.",
    "A larger window increases potential throughput but needs buffering and does not overcome arbitrary loss or path limits.",
    "The highest received sequence is not always the highest contiguous confirmed sequence.",
    "Can a receiver ACK progress beyond a gap without clarifying the ACK scheme?",
    "Different protocols report different kinds of information.",
    "State whether the ACK is cumulative, next-expected or selective. A cumulative acknowledgment alone must not claim the missing earlier data arrived.",
    "Declare the ACK convention|Trace gaps and contiguous progress|Separate receiver capacity from path congestion",
  ),
  "shortest-routing": u(
    "Weighted graphs|Path cost|Reachability",
    "A route’s cost is the sum of its edge weights, not just its hop count. Dijkstra’s method is suitable for nonnegative weights; topology changes require recomputation or an update mechanism. Convergence and distributed protocol behavior are separate from this small centralized model.",
    "Edges are A→B=2, B→C=2 and A→C=7. Find the cheapest A-to-C route.",
    "The direct route costs 7.|The route through B costs 2+2=4.|Choose A→B→C under these fixed nonnegative weights.",
    "A→B→C, total cost 4.",
    "Choose the fewest hops without accounting for edge costs.",
    "Relax cumulative path costs using an algorithm valid for the weight assumptions.",
    "A changed graph can invalidate a previous route; distributed convergence and policy add complexity.",
    "A greedy nearest-next-hop choice is not a general shortest-path proof.",
    "If B→C fails, what changes?",
    "Remove unavailable edges before comparing paths.",
    "The route through B is no longer available. In this graph, use direct A→C at cost 7; if that edge also fails, report C unreachable.",
    "Add edge costs correctly|Check algorithm assumptions|Handle topology changes and unreachable destinations",
  ),
  "congestion-control": u(
    "Feedback loops|Offered load versus capacity",
    "Congestion control adjusts what a sender offers to the path. Additive increase probes cautiously; multiplicative decrease reduces load after a congestion signal. The lab uses a simple per-round capacity threshold. It does not reproduce every TCP state, RTT effect or queue behavior.",
    "The current sending window is 8 and the lab halves it after loss. What is the next window, and what happens after one successful additive-increase round?",
    "On the loss signal, compute max(1,floor(8/2)) = 4.|Send under the reduced window according to the model.|After a successful additive-increase round, increase the next window from 4 to 5.",
    "Next windows are 4 after loss and 5 after the stated success.",
    "Use a fixed sending window regardless of feedback.",
    "Adapt offered load to congestion signals using a defined control rule.",
    "More aggressive probing can improve utilization but worsen queues and fairness; feedback is imperfect.",
    "The sending window is not the number of bytes guaranteed to arrive or an exact path-capacity measurement.",
    "What happens if a fixed window 8 repeatedly faces capacity 3 in the lab?",
    "Separate offered traffic from successful delivery.",
    "Each round offers more than the threshold; at most 3 units are delivered per round in this model and the sender ignores the loss feedback. Real network outcomes depend on buffering and transport details.",
    "Trace the control update|Distinguish offered and delivered work|State simplified feedback assumptions",
  ),
  encapsulation: u(
    "Classes and object state|Preconditions|Public methods",
    "Encapsulation places state and the rules for changing it behind a controlled interface. The goal is preserving meaningful invariants rather than mechanically making every field private. Callers should express domain operations instead of assembling unsafe sequences of low-level changes.",
    "An account holds 50. A withdrawal request is 70, and the invariant forbids negative balance. What should its operation do?",
    "Validate amount and funds before committing the mutation.|Since 70 exceeds 50, reject the operation.|Leave the balance at 50; do not subtract and hope the caller repairs it.",
    "Rejected withdrawal; balance remains 50.",
    "Let callers write balance directly.",
    "Expose deposit and withdraw operations with invariant checks.",
    "A larger interface can hide too little or too much; concurrency and persistence still require explicit rules.",
    "A setter that accepts every value does not meaningfully protect the invariant.",
    "What if two concurrent withdrawals of 40 both read balance 50?",
    "Encapsulation alone does not make the method atomic.",
    "Both can pass the check using old state. Protect check-and-update together with a transaction, synchronization or an appropriate atomic operation.",
    "Name the invariant|Control its mutation boundary|Separate encapsulation from concurrency guarantees",
  ),
  "strategy-pattern": u(
    "Interfaces|Composition|Delegation",
    "Strategy gives a context a replaceable implementation of one behavior. The context calls the common contract; the selected strategy decides the algorithm. The selection rule and each algorithm’s correctness remain explicit responsibilities.",
    "A cart totals 100. Compare a 10% discount strategy with a fixed 15-unit discount.",
    "The percentage strategy subtracts 100×0.10 = 10.|The fixed strategy subtracts 15.|Both return through the same pricing contract, giving 90 and 85 respectively.",
    "Percentage result 90; fixed result 85 under the stated rules.",
    "Put every discount branch inside one large cart method.",
    "Delegate discount calculation to a strategy selected by a caller or policy.",
    "Extra abstractions have a maintenance cost; a stable pair of trivial cases may not need the pattern.",
    "Strategy does not decide which behavior is appropriate unless you design that selection policy.",
    "A fixed discount exceeds the subtotal. Where should the nonnegative-total rule live?",
    "Define the common contract before swapping implementations.",
    "Specify whether strategies clamp, reject or permit negative totals. Enforce the rule consistently at the pricing boundary, and test every implementation against it.",
    "Identify the varying behavior|Define a shared contract|Test substitutable implementations",
  ),
  "observer-pattern": u(
    "Events and listeners|Registration|State updates",
    "A publisher emits an event to registered observers. This decouples the publisher from each reaction, but callback ordering, failures, duplicate subscriptions and removal during notification need rules. Local observer callbacks are not automatically a reliable distributed event bus.",
    "Observers Chart and Audit are registered. Alert is not. A price-change event fires. Who receives it?",
    "Take the subscriber set defined by the notification contract.|Notify Chart and Audit with the same logical event.|Do not notify Alert just because its class exists.",
    "Chart and Audit receive the event; Alert does not.",
    "Hard-code every response into the publisher.",
    "Manage subscriptions and deliver through a common observer contract.",
    "Delivery may be synchronous and slow; independent failures need an explicit handling policy.",
    "Observer alone promises no persistence, exactly-once delivery or cross-process reliability.",
    "Audit throws an exception. Must Chart still be notified?",
    "That depends on the failure-isolation contract.",
    "Define whether notification stops or isolates each subscriber failure. If every observer must be attempted, capture errors per callback and record them without silently reporting complete success.",
    "Track the registered set|Define callback failure semantics|Distinguish local events from durable messaging",
  ),
  "factory-pattern": u(
    "Construction versus use|Interfaces|Input validation",
    "A factory centralizes selecting and constructing an implementation. Callers receive an object through a useful contract rather than repeating type-selection code. Factories do not guarantee that all possible products have identical behavior; the promised interface must be honest.",
    "A notification request chooses email. Which responsibility belongs to the factory?",
    "Validate that email is a supported channel.|Construct or obtain the email implementation.|Return it through the delivery interface.|Let the implementation handle email-specific delivery according to that interface.",
    "Selection and construction belong to the factory; sending follows the delivery contract.",
    "Repeat construction branches at every call site.",
    "Centralize implementation selection and validate unsupported choices.",
    "Central construction can become overcomplicated; configuration and object lifetimes still require decisions.",
    "A factory is not automatically a singleton or a dependency-injection container.",
    "A client asks for an unsupported channel. What should happen?",
    "Avoid returning an unrelated implementation silently.",
    "Return a clear construction or validation failure. If a fallback is intentionally supported, make it an explicit part of the API and observable to the caller.",
    "Separate creation from use|Handle unsupported variants|Explain object lifetime and configuration",
  ),
  "adapter-pattern": u(
    "Interfaces and expected units|Composition|Translation",
    "An adapter translates one interface into another contract expected by a caller. Translation includes meaning, units, errors and lifecycle, not just method names. It should avoid silently losing information or changing the operation’s guarantees.",
    "A caller expects cents. A legacy provider returns a monetary value of 12.50 units. What conversion is needed?",
    "Declare that one unit equals 100 cents.|Convert the provider’s value to 1,250 cents using an appropriate exact-decimal or integer representation.|Translate provider errors into the caller’s documented error contract.",
    "1,250 cents, with rounding behavior explicitly defined.",
    "Make callers understand each provider’s names and units.",
    "Place the translation in an adapter exposing the required interface.",
    "Conversions can lose precision or meaning; unsupported operations must be reported.",
    "An adapter cannot manufacture a guarantee that the underlying service does not provide.",
    "The provider returns a value with three decimal places. What must the adapter decide?",
    "The caller’s cents contract has only two decimal places.",
    "Specify rounding, rejection or a finer internal unit. Use exact monetary representations and test boundary cases rather than relying on accidental binary floating-point behavior.",
    "Translate units and errors|Preserve stated semantics|Handle lossy conversions explicitly",
  ),
  "decorator-pattern": u(
    "Composition|Wrapping an interface|Operation ordering",
    "A decorator wraps another implementation and augments a compatible operation. Several wrappers can be composed, but their order can change the result. Follow the complete call chain rather than assuming that a set of wrappers behaves like an unordered set.",
    "Start with 100. Compare add-10 then multiply-by-2 with multiply-by-2 then add-10.",
    "In the first order: (100+10)×2 = 220.|In the second order: 100×2+10 = 210.|Map each operation to its position in the wrapper chain.",
    "220 versus 210; the order is observable.",
    "Create a new subclass for every combination of optional behavior.",
    "Compose wrappers with a clear interface and a documented order.",
    "Long chains complicate debugging and resource ownership; some augmentations do not commute.",
    "Wrapping preserves an interface, not automatic equivalence of every composition order.",
    "A wrapper logs once per call. Compare logging outside a retry wrapper with logging inside it.",
    "Follow the call chain for one logical request that needs two attempts.",
    "With one outer logging call around the retry wrapper, a logical operation can produce one log entry. When the retry wrapper calls a logging-wrapped attempt twice, it can produce two entries. Specify whether the log describes logical operations, attempts or outcomes.",
    "Trace the wrapper order|Show a noncommutative example|Explain interface and resource-lifetime constraints",
  ),
};
