export type PatternUnit = {
  recognize: string;
  baseline: string;
  improvement: string;
  proof: string;
  pitfall: string;
  challenge: string;
};
const p = (
  recognize: string,
  baseline: string,
  improvement: string,
  proof: string,
  pitfall: string,
  challenge: string,
): PatternUnit => ({
  recognize,
  baseline,
  improvement,
  proof,
  pitfall,
  challenge,
});
export const patternUnits: PatternUnit[] = [
  p(
    "A contiguous range must satisfy a size, uniqueness or frequency rule.",
    "Enumerate candidate substrings/subarrays and recompute each candidate’s state.",
    "Maintain a valid range and update only the elements entering or leaving it.",
    "Define exactly when the range is valid and why shrinking or extending cannot skip the required optimum.",
    "A variable window needs a justified monotone shrink rule. Fixed windows still need a valid initial answer for negative inputs.",
    "Explain which stored quantity changes when one element leaves. Show an input where an incorrect initial best value fails.",
  ),
  p(
    "Ordered boundaries or endpoint geometry let one side be eliminated safely.",
    "Inspect every pair of endpoints.",
    "Move the boundary whose elimination is supported by order or a problem-specific bound.",
    "Prove that every pair involving the discarded boundary cannot improve the required answer under the current condition.",
    "Sorted-pair reasoning cannot be used unchanged for an unsorted array; water-area and rain-water proofs use different bounds.",
    "Explain a single pointer move using an inequality. Identify the assumption that makes it safe.",
  ),
  p(
    "Two walkers at different speeds reveal a meeting, midpoint or cycle structure.",
    "Store every visited node identity, or repeatedly scan the path.",
    "Use controlled relative motion and then a second phase if the entrance is needed.",
    "Reason about distance around the cycle and the noncyclic prefix, rather than claiming that any repeated value is a repeated node.",
    "Equal node values do not imply equal node identities; guard missing next links.",
    "Draw a short prefix feeding a cycle. Explain why detecting a meeting and finding the entrance are separate tasks.",
  ),
  p(
    "An item waits for the next larger/smaller boundary, with a useful stack order.",
    "Scan forward from each item to find its answer.",
    "Keep unresolved candidates on a monotone stack and resolve them when a violating item arrives.",
    "Each candidate is inserted once and removed at most once, bounding total stack operations linearly.",
    "Choose strict versus non-strict comparison intentionally; equal values can change the required result.",
    "Show why a popped candidate never needs to be reinserted. Count pushes and pops instead of multiplying nested-loop bounds.",
  ),
  p(
    "Nested structure or a left-to-right expression needs pending state.",
    "Repeatedly find and remove local valid pieces or reparsed expressions.",
    "Store pending delimiters or operands on a stack and resolve them in a defined order.",
    "State what each stack entry represents for the already processed prefix.",
    "Operand order matters for subtraction/division; delimiters need matching types, not only a balance count.",
    "Trace one valid nested case and one invalid closing token. Explain why your prefix invariant rejects it.",
  ),
  p(
    "Ranges overlap, consume resources or must be inserted into an ordered set.",
    "Compare every interval with every other interval.",
    "Sort endpoints or intervals, then maintain the active merged range or resource count.",
    "After sorting, explain why earlier completed ranges cannot overlap a future range under the endpoint convention.",
    "Closed intervals, half-open meetings and touching endpoints require different tie rules.",
    "Choose a pair of touching intervals. Explain exactly whether they merge or can reuse a room.",
  ),
  p(
    "Links must be rewired while retaining access to the remaining chain.",
    "Copy values into another container and build a new chain.",
    "Maintain previous/current/next references and rewire only after saving the continuation.",
    "The reversed processed prefix and untouched suffix remain reachable and correctly connected.",
    "Overwriting next before saving it can lose the rest of the list. Partial reversals need reconnection at both boundaries.",
    "Draw three nodes and perform one pointer update. Identify which reference prevents the suffix from becoming unreachable.",
  ),
  p(
    "The predicate changes from false to true, or a sorted search region can shrink safely.",
    "Inspect every candidate answer or every array element.",
    "Binary-search a declared interval using a monotone predicate and strict progress.",
    "The required answer remains in the candidate interval; each update excludes only impossible candidates.",
    "An answer-space predicate must really be monotone. Define inclusive/half-open bounds and what is returned when no answer exists.",
    "Write the predicate in one sentence. Test values on both sides of its transition before choosing a midpoint update.",
  ),
  p(
    "A rotated ordered array contains ordered regions and a pivot.",
    "Linearly inspect all values.",
    "Identify a sorted region and determine whether the target or minimum can lie within it.",
    "Each eliminated region must be incompatible with the target/minimum under the ordering and equality assumptions.",
    "Duplicates can obscure which half is ordered and degrade worst-case time; equality cases cannot always halve the range.",
    "Create a rotated input with duplicate boundary values. Explain why an ambiguous comparison needs extra handling.",
  ),
  p(
    "The problem asks about levels, nearest depth or breadth-first processing.",
    "Repeatedly walk the tree to discover each depth.",
    "Use a queue and process exactly the current level’s size before the next level.",
    "All nodes dequeued in the current batch have the same depth; their children belong to the next depth.",
    "Taking a changing queue size inside the level loop can mix levels. Missing children are not actual nodes.",
    "Explain why a leaf first reached by BFS has minimum depth, then distinguish that from maximum-depth computation.",
  ),
  p(
    "A subtree’s result depends on its descendants or a root-to-node path.",
    "Recompute descendant or path information from scratch at each node.",
    "Use DFS with an explicit return meaning and appropriate path state.",
    "For each call, say which subtree/path the return value describes, and show how child results compose.",
    "Path-local state must be restored between siblings; global-best and returned values may serve different purposes.",
    "Write the return contract of one recursive call. Explain a case where returning a global maximum would be incorrect.",
  ),
  p(
    "Many queries share prefixes or need branching character lookups.",
    "Scan each stored word from the beginning for every query.",
    "Share prefix paths in a trie and store an explicit terminal marker.",
    "Every root-to-node path spells a stored prefix; only terminal nodes represent complete words.",
    "A prefix existing in the trie does not prove the whole word was inserted. Wildcards may explore many branches.",
    "Insert a word and its shorter prefix. Explain why the terminal flags must be independent.",
  ),
  p(
    "Values have a constrained expected position, often in a bounded integer range.",
    "Sort or store frequencies in extra memory.",
    "Place each eligible value at its designated position while avoiding duplicate-swap loops.",
    "Each useful swap places a value in a valid home or advances detection of a duplicate/out-of-range value.",
    "Position formulas depend on whether values start at zero or one; out-of-range values must never be used as indices.",
    "Give an input with a duplicate and an out-of-range value. Show how both avoid an infinite swapping loop.",
  ),
  p(
    "Adjacency is defined by neighboring coordinates in a grid.",
    "For each cell, repeatedly rediscover the same connected region or path.",
    "Use a visited rule and a traversal whose neighbors match the problem’s movement contract.",
    "Every eligible cell is processed as intended, and boundary checks happen before access.",
    "Diagonal versus side adjacency changes connectivity. DFS visitation and shortest-path BFS are different goals.",
    "Construct two cells touching only diagonally. Explain whether the problem considers them connected.",
  ),
  p(
    "Dependencies must precede dependents, and cycles can invalidate the ordering.",
    "Repeatedly search for a task with no remaining prerequisites.",
    "Track indegrees and enqueue zero-indegree vertices, or use a DFS state discipline.",
    "A vertex becomes ready only after all its incoming dependencies have been satisfied.",
    "Edge direction must match the prerequisite contract. Producing fewer than all vertices signals a cycle or inconsistent processing.",
    "Draw a two-vertex cycle. Explain why neither vertex can be scheduled by the zero-indegree queue.",
  ),
  p(
    "Repeated connectivity queries concern undirected components.",
    "Run a full graph traversal for every connectivity request.",
    "Maintain representatives with union operations, using rank/size and path compression where appropriate.",
    "Two vertices share a representative exactly when the processed edges connect them, under the update contract.",
    "Union-find alone does not supply directed reachability, shortest paths or arbitrary deletions.",
    "Add an edge joining two existing components. Explain which component count changes and why a within-component edge changes none.",
  ),
  p(
    "The answer is a minimum accumulated path cost or an analogous optimal path quantity.",
    "Enumerate all paths, which may grow exponentially or fail to terminate around cycles.",
    "Select an algorithm matched to edge weights and constraints: BFS, Dijkstra, Bellman-Ford or a constrained-state method.",
    "Explain why the chosen relaxation/finalization rule is valid for the allowed weights or expanded states.",
    "Dijkstra needs nonnegative edge weights. A stop budget can require separate states for the same vertex.",
    "Show a graph where the route with fewer hops costs more. Explain which algorithm handles the actual objective.",
  ),
  p(
    "A stream or changing frontier repeatedly needs the best/smallest/largest candidate.",
    "Resort the entire collection after each update.",
    "Use a heap with a clearly stated ordering and, for top-k problems, a bounded retained set.",
    "The heap root satisfies its ordering rule; the retained-set invariant explains which discarded candidates can never enter the answer.",
    "A heap is not a fully sorted array. Comparator direction and stale entries affect correctness.",
    "For top-k largest values, explain why a min-heap of size k exposes the candidate that can be discarded next.",
  ),
  p(
    "The solution explores combinations of choices, with constraints and reversals.",
    "Generate every complete candidate and test constraints only at the end.",
    "Choose, explore and undo; prune only branches proven unable to yield a required answer.",
    "Each recursion level fixes a choice and restores shared state before the next sibling branch.",
    "Deduplication must match the problem’s notion of distinct answers. Early pruning without proof can remove valid solutions.",
    "Name the state changed by one choice and its exact undo operation. Explain why a proposed prune is safe.",
  ),
  p(
    "A one-dimensional position or amount has reusable smaller answers.",
    "Use direct recursive enumeration with repeated overlapping calls.",
    "Define a state meaning, base cases and recurrence, then memoize or fill in dependency order.",
    "Each transition combines already correct answers to exactly the smaller subproblems described by the state.",
    "Initialization of impossible states differs from zero-valued valid states; update order can change reuse rules.",
    "Explain whether ascending or descending updates permit reusing an item more than once.",
  ),
  p(
    "Two positions or dimensions jointly determine a reusable subproblem.",
    "Explore every pair of remaining choices recursively.",
    "Define the pair of indices precisely and reuse a table or memo keyed by both dimensions.",
    "A cell’s meaning specifies its consumed prefixes or remaining suffixes, making each recurrence and boundary case checkable.",
    "Off-by-one boundaries and confusing prefixes with suffixes cause incorrect recurrences.",
    "Draw a 2×3 table. Label exactly what one cell means before performing any arithmetic.",
  ),
  p(
    "Simple states are insufficient because history, intervals or modes change future options.",
    "Enumerate complete histories and recompute their costs.",
    "Find the smallest state that preserves all information relevant to future decisions, then order dependencies correctly.",
    "Histories merged into the same state must have equivalent future possibilities for the optimization objective.",
    "Dropping a relevant mode, previous action or interval boundary can make memoization incorrect.",
    "Give two partial histories that look similar but permit different next moves. Explain which extra state separates them.",
  ),
  p(
    "A locally optimal choice may remain compatible with some globally optimal solution.",
    "Enumerate all possible schedules or selections.",
    "Choose by a justified rule and maintain feasibility after each choice.",
    "Use an exchange argument, dominance bound or another specific proof that replacing an optimal choice loses nothing.",
    "A plausible local heuristic is not automatically correct. Counterexamples matter before optimization.",
    "Try to break the local rule with a tiny adversarial input; if it survives, state the exchange argument.",
  ),
  p(
    "Bits encode independent flags, parity or a fixed-width representation.",
    "Convert everything to strings or count individual values in extra structures.",
    "Use masks, shifts and algebraic identities under a declared width and signedness contract.",
    "Show the bit-level identity and account for every permitted input, including zero and negative representations.",
    "Shifts, signed overflow and integer width vary across languages. XOR cancellation requires the stated multiplicity assumptions.",
    "Write a two’s-complement example and explain how the operation behaves under the chosen width.",
  ),
  p(
    "Strings share prefix/suffix structure or fixed-size encodings that can avoid repeated scans.",
    "Compare each pattern position from scratch or store every full substring copy.",
    "Reuse prefix/failure information or a bounded rolling encoding with an explicit equality check where needed.",
    "The stored prefix/encoding describes exactly the portion of text already processed and supports safe reuse.",
    "A hash collision is not string equality. Failure tables need correct fallback, and separators must be outside the input alphabet when required.",
    "Trace a mismatch after a partial match. Explain why the fallback prefix still matches the relevant suffix.",
  ),
];
