import type { CourseUnit } from "./cs-course-content";
const f = (
  pre: string,
  concept: string,
  prompt: string,
  steps: string,
  answer: string,
  baseline: string,
  improved: string,
  tradeoff: string,
  misconception: string,
  transfer: string,
  hint: string,
  solution: string,
  rubric: string,
): CourseUnit => ({
  prerequisites: pre.split("|"),
  concept,
  worked: { prompt, steps: steps.split("|"), answer },
  comparison: { baseline, improved, tradeoff },
  misconception,
  transfer: { prompt: transfer, hint, solution },
  rubric: rubric.split("|"),
});
export const foundationCourseContent: Record<string, CourseUnit> = {
  "binary-search": f(
    "Ascending order|Zero-based indices|Inclusive interval bounds",
    "Binary search repeatedly chooses the middle of a valid candidate interval. If the middle value is below the target, everything at or left of it is too small. If it is above the target, everything at or right of it is too large. The discarded middle must not remain in the next interval.",
    "Find target 14 in [2,4,7,9,11,14,18,21].",
    "Start with indices [0,7]. mid=floor((0+7)/2)=3, whose value is 9.|Since 9 < 14, move left to 4. The remaining interval is [4,7].|mid=floor((4+7)/2)=5, whose value is 14. Return index 5.",
    "The zero-based result is 5. Two midpoint comparisons find the target.",
    "Scan values from left to right: O(n) worst-case comparisons.",
    "Halve a sorted candidate region: O(log n) comparisons and O(1) extra space iteratively.",
    "Sorting first costs O(n log n) and can change indices; use binary search when ordered access or a monotone predicate is available.",
    "Using left = mid rather than mid + 1 can fail to shrink the interval.",
    "Search [4] for target 7. Why must the method finish?",
    "Trace the one candidate and the next interval.",
    "Check index 0, observe 4 < 7, then set left=1. The interval [1,0] is empty, so return -1.",
    "Keep the target inside the candidate interval|Exclude the checked midpoint|Handle one-element and missing-target cases",
  ),
  "two-sum": f(
    "Sorted values|Distinct indices|How a sum changes when a pointer moves",
    "Two pointers exploit sorted order to eliminate whole groups of pairs. When the smallest remaining value plus the largest remaining value is too small, that smallest value cannot work with any remaining partner. The symmetric rule applies to an excessive sum.",
    "Find target 11 in sorted [1,3,4,8].",
    "Compare indices 0 and 3: 1+8=9, too small.|Discard index 0 and compare indices 1 and 3: 3+8=11.|Return the distinct zero-based pair [1,3].",
    "Result [1,3]. The foundation uses zero-based indices.",
    "Try every pair: O(n²) time and O(1) extra space.",
    "Move inward over a sorted array: O(n) time and O(1) extra space.",
    "Sorting an unsorted input costs time and may require tracking original positions. A hash-map method offers another time/space trade-off.",
    "The sorted-input elimination proof does not apply unchanged to arbitrary input order.",
    "Can one element [5] supply target 10?",
    "The contract requires two different positions.",
    "No. left and right would be equal; stop before using one element twice. A repeated value at two different positions can form a valid pair.",
    "Justify each eliminated boundary|Respect distinct positions|State sortedness and indexing rules",
  ),
  "sliding-window": f(
    "Contiguous subarrays|A fixed window size|Addition and subtraction",
    "Adjacent fixed-size windows share k−1 values. Keep the sum and replace just the outgoing and incoming contributions. A complete update changes both contributions; an intermediate sum after only the addition is not yet a valid next window.",
    "Find the maximum sum of a length-2 window in [-5,-2,-4].",
    "Initialize from the first real window: -5 + -2 = -7.|Slide one position: remove -5 and add -4, giving -7 - (-5) + (-4) = -6.|Compare the two valid sums. The maximum is -6.",
    "Maximum window sum -6, not zero.",
    "Sum all k values for each window: O((n−k+1)k) time.",
    "Compute one initial sum, then two updates per slide: O(n) time and O(1) extra space.",
    "This fixed-window rule does not directly solve every variable-length or noncontiguous selection problem.",
    "Initializing best to zero produces an invalid answer when every valid sum is negative.",
    "If k equals the full array length, how many valid windows exist?",
    "A window must fit completely inside the input.",
    "Exactly one. Sum the whole array and return that sum; no sliding update is needed.",
    "Update a complete valid window|Initialize best from actual data|Check k and negative inputs",
  ),
  "bubble-sort": f(
    "Adjacent comparisons|In-place mutation|Temporary storage",
    "Each adjacent comparison can move a larger value one place right. A complete pass settles the largest remaining value at the right boundary. The settled suffix can be excluded from later passes; a temporary variable preserves a value before its slot is overwritten.",
    "Perform the first pass on [4,1,3].",
    "Compare 4 and 1, then swap them: [1,4,3].|Compare 4 and 3, then swap them: [1,3,4].|The maximum 4 is settled at the last index. The next pass only considers the remaining prefix.",
    "After the first pass: [1,3,4], with the final value settled.",
    "Continue comparing the full array without exploiting the settled suffix.",
    "Shrink the active end after each completed pass. The shown reference still has O(n²) time and O(1) extra space.",
    "Bubble sort is useful for understanding local swaps; library sorting generally provides better practical performance for large inputs.",
    "Shrinking the end saves work but does not make this reference implementation linear on an already sorted input.",
    "How could an optimized variant finish early on an already sorted array?",
    "A pass with no swaps gives information about the full active region.",
    "Track whether a pass swapped anything. If no adjacent pair is out of order during a full pass, the region is sorted and the algorithm can stop. That optimization is separate from the displayed reference.",
    "Explain the settled suffix|Preserve overwritten values|Distinguish the reference from an early-exit variant",
  ),
  "insertion-sort": f(
    "A sorted prefix|Shifting values|A held key",
    "Insertion sort grows a sorted prefix. Hold the next value in key, shift larger prefix values right, and insert key into the resulting gap. The temporary key is essential because shifting can overwrite its original array position.",
    "Insert the last value of [2,5,3] into the already sorted prefix [2,5].",
    "Hold key=3 and begin at the preceding value 5.|Since 5 > 3, shift 5 right. The intermediate array is [2,5,5], while key still holds 3.|Stop at 2, which is not greater than key. Place 3 into the gap to obtain [2,3,5].",
    "Sorted array [2,3,5]. The duplicate-looking intermediate state is expected during a shift.",
    "Build a new sorted container by repeatedly scanning an insertion position.",
    "Shift in place while keeping one key: O(n²) worst-case time and O(1) extra space.",
    "Already ordered inputs require little shifting; large reversed inputs require many. Stability depends on the equality handling.",
    "An intermediate repeated value is not necessarily a lost element: the original value can be held in key.",
    "Should equal values shift when stability is desired?",
    "Preserve the relative order of equal-key elements.",
    "Use a strict greater-than comparison for shifts in this approach. An equal previous value remains before the held equal value, preserving their original order.",
    "Maintain the sorted prefix|Protect the held key|Explain shift count and equality handling",
  ),
  "prefix-sum": f(
    "Array indices|Cumulative totals|Half-open ranges",
    "The prefix array stores how much total lies before each boundary. prefix[0]=0 and prefix[i+1]=prefix[i]+nums[i]. Subtracting two boundary totals cancels everything before the range. The extra slot represents the boundary before the first value.",
    "Build prefix sums for [2,-1,4] and query the inclusive range [1,2].",
    "Build prefix=[0,2,1,5].|The total through index 2 is prefix[3]=5.|Remove everything before index 1 using prefix[1]=2: 5−2=3.",
    "Range [1,2] sums to 3.",
    "Sum every requested range from scratch: up to O(n) per query.",
    "Build O(n) prefix totals, then answer a static range-sum query in O(1). Extra storage is O(n).",
    "Changing an input value invalidates later prefix totals. Frequently updated data may need a different structure.",
    "For inclusive [left,right], use prefix[right+1]−prefix[left], not prefix[right]−prefix[left].",
    "What changes after nums[1] changes from -1 to 3?",
    "Identify every cumulative total that includes that input position.",
    "prefix[0] and prefix[1] stay the same. Every boundary after index 1 increases by 4, producing [0,2,5,9].",
    "Define every prefix boundary|Use the inclusive-range conversion|Explain preprocessing and update costs",
  ),
};
