import {javascriptAdvanced} from "./javascript-advanced";
const bodies:Record<string,string>={
"longest-unique-substring":`const {s}=d, last=new Map(); let left=0,best=0;
for(let right=0;right<s.length;right++){if(last.has(s[right]))left=Math.max(left,last.get(s[right])+1);last.set(s[right],right);best=Math.max(best,right-left+1);trace({s,left,right,best});}return best;`,
"character-replacement":`const {s,k}=d,counts={};let left=0,most=0,best=0;
for(let right=0;right<s.length;right++){counts[s[right]]=(counts[s[right]]||0)+1;most=Math.max(most,counts[s[right]]);while(right-left+1-most>k)counts[s[left++]]--;best=Math.max(best,right-left+1);trace({s,left,right,best,counts});}return best;`,
"minimum-window":`const {s,t}=d;if(!t)return '';const need={};for(const c of t)need[c]=(need[c]||0)+1;let left=0,missing=t.length,start=0,best=Infinity;
for(let right=0;right<s.length;right++){if((need[s[right]]||0)>0)missing--;need[s[right]]=(need[s[right]]||0)-1;while(!missing){if(right-left+1<best){best=right-left+1;start=left;}if(++need[s[left++]]>0)missing++;}trace({s,left,right,missing,best,need});}return best===Infinity?'':s.slice(start,start+best);`,
"three-sum":`const nums=[...d.nums].sort((a,b)=>a-b),result=[];for(let i=0;i<nums.length-2;i++){if(i&&nums[i]===nums[i-1])continue;let left=i+1,right=nums.length-1;while(left<right){const total=nums[i]+nums[left]+nums[right];trace({nums,i,left,right,total,result});if(total<0)left++;else if(total>0)right--;else{result.push([nums[i],nums[left],nums[right]]);const a=nums[left],b=nums[right];while(left<right&&nums[left]===a)left++;while(left<right&&nums[right]===b)right--;}}}return result;`,
"container-water":`const {height}=d;let left=0,right=height.length-1,best=0;while(left<right){best=Math.max(best,(right-left)*Math.min(height[left],height[right]));trace({height,left,right,best});if(height[left]<height[right])left++;else right--;}return best;`,
"trapping-rain":`const {height}=d;let left=0,right=height.length-1,lmax=0,rmax=0,water=0;while(left<=right){if(lmax<=rmax){lmax=Math.max(lmax,height[left]);water+=lmax-height[left++];}else{rmax=Math.max(rmax,height[right]);water+=rmax-height[right--];}trace({height,left,right,lmax,rmax,water});}return water;`,
"middle-list":`const nodes=d.values,links=makeLinks(nodes.length);let slow=nodes.length?0:-1,fast=slow;while(fast!==-1&&links[fast]!==-1){slow=links[slow];fast=links[links[fast]];trace({nodes,links,slow,fast});}return walk(nodes,links,slow);`,
"linked-cycle":`const nodes=d.values,links=makeLinks(nodes.length,d.pos??-1);let slow=nodes.length?0:-1,fast=slow;while(fast!==-1&&links[fast]!==-1){slow=links[slow];fast=links[links[fast]];trace({nodes,links,slow,fast});if(slow===fast)return true;}return false;`,
"cycle-entrance":`const nodes=d.values,links=makeLinks(nodes.length,d.pos??-1);let slow=nodes.length?0:-1,fast=slow;while(fast!==-1&&links[fast]!==-1){slow=links[slow];fast=links[links[fast]];trace({nodes,links,slow,fast});if(slow===fast){slow=0;while(slow!==fast){slow=links[slow];fast=links[fast];trace({nodes,links,slow,fast});}return slow;}}return -1;`,
"duplicate-number":`const {nums}=d;let slow=0,fast=0;do{slow=nums[slow];fast=nums[nums[fast]];trace({nums,slow,fast});}while(slow!==fast);slow=0;while(slow!==fast){slow=nums[slow];fast=nums[fast];trace({nums,slow,fast});}return slow;`,
"next-greater":`const nums=d.nums2,stack=[],next=new Map();for(let i=0;i<nums.length;i++){while(stack.length&&stack.at(-1)<nums[i])next.set(stack.pop(),nums[i]);stack.push(nums[i]);trace({nums,stack,i,next});}return d.nums1.map(v=>next.get(v)??-1);`,
"daily-temperatures":`const {temperatures}=d,stack=[],result=Array(temperatures.length).fill(0);for(let i=0;i<temperatures.length;i++){while(stack.length&&temperatures[i]>temperatures[stack.at(-1)]){const j=stack.pop();result[j]=i-j;}stack.push(i);trace({temperatures,stack,result,i});}return result;`,
"car-fleet":`const cars=d.position.map((p,i)=>[p,d.speed[i]]).sort((a,b)=>b[0]-a[0]),stack=[];for(const [position,speed]of cars){const arrival=(d.target-position)/speed;if(!stack.length||arrival>stack.at(-1))stack.push(arrival);trace({stack,position,arrival});}return stack.length;`,
"largest-rectangle":`const heights=[...d.heights,0],stack=[];let best=0;for(let i=0;i<heights.length;i++){while(stack.length&&heights[stack.at(-1)]>heights[i]){const h=heights[stack.pop()],left=stack.length?stack.at(-1):-1;best=Math.max(best,h*(i-left-1));trace({heights,stack,i,left,best});}stack.push(i);}return best;`,
"valid-parentheses":`const {s}=d,stack=[],pairs={')':'(',']':'[','}':'{'};for(let i=0;i<s.length;i++){const c=s[i];if(c in pairs){if(stack.pop()!==pairs[c])return false;}else stack.push(c);trace({s,stack,i});}return stack.length===0;`,
"reverse-polish":`const stack=[];for(const token of d.tokens){if(['+','-','*','/'].includes(token)){if(stack.length<2)throw Error('Missing operand');const b=stack.pop(),a=stack.pop();if(token==='/'&&b===0)throw Error('Division by zero');stack.push(token==='+'?a+b:token==='-'?a-b:token==='*'?a*b:Math.trunc(a/b));}else stack.push(Number(token));trace({stack,token});}return stack[0];`,
"min-stack":`const stack=[],minima=[],result=[];for(const [name,value]of d.operations){if(name==='push'){stack.push(value);minima.push(Math.min(value,minima.at(-1)??Infinity));result.push(null);}else{if(!stack.length)throw Error('Empty stack');if(name==='pop'){stack.pop();minima.pop();result.push(null);}else result.push(name==='top'?stack.at(-1):minima.at(-1));}trace({stack,minima,result});}return result;`,
"calculator-ii":`const s=d.s+'+',stack=[];let value=0,operation='+';for(let i=0;i<s.length;i++){const c=s[i];if(c>='0'&&c<='9')value=value*10+Number(c);else if(c!==' '){if(operation==='+')stack.push(value);else if(operation==='-')stack.push(-value);else if(operation==='*')stack.push(stack.pop()*value);else{if(value===0)throw Error('Division by zero');stack.push(Math.trunc(stack.pop()/value));}operation=c;value=0;trace({s,stack,i});}}return stack.reduce((a,b)=>a+b,0);`,
"merge-intervals":`const intervals=d.intervals.map(v=>[...v]).sort((a,b)=>a[0]-b[0]),result=[];for(const interval of intervals){if(!result.length||interval[0]>result.at(-1)[1])result.push(interval);else result.at(-1)[1]=Math.max(result.at(-1)[1],interval[1]);trace({intervals,result});}return result;`,
"insert-interval":`const {intervals}=d,added=[...d.newInterval],result=[];let i=0;while(i<intervals.length&&intervals[i][1]<added[0])result.push(intervals[i++]);while(i<intervals.length&&intervals[i][0]<=added[1]){added[0]=Math.min(added[0],intervals[i][0]);added[1]=Math.max(added[1],intervals[i++][1]);trace({intervals,added,result,i});}result.push(added);while(i<intervals.length)result.push(intervals[i++]);trace({result});return result;`,
"meeting-rooms":`const events=d.intervals.flatMap(([a,b])=>[[a,1],[b,-1]]).sort((a,b)=>a[0]-b[0]||a[1]-b[1]);let rooms=0,best=0;for(const [time,delta]of events){rooms+=delta;best=Math.max(best,rooms);trace({time,rooms,best});}return best;`,
"burst-balloons-arrows":`const intervals=[...d.points].sort((a,b)=>a[1]-b[1]);let boundary=-Infinity,arrows=0;for(const [start,end]of intervals){if(start>boundary){arrows++;boundary=end;}trace({intervals,boundary,arrows});}return arrows;`,
"reverse-list":`const nodes=d.values,links=makeLinks(nodes.length);let previous=-1,current=nodes.length?0:-1;while(current!==-1){const following=links[current];links[current]=previous;previous=current;current=following;trace({nodes,links,previous,current,following});}return walk(nodes,links,previous);`,
"reorder-list":`const nodes=d.values,links=makeLinks(nodes.length);if(!nodes.length)return [];let slow=0,fast=0;while(links[fast]!==-1&&links[links[fast]]!==-1){slow=links[slow];fast=links[links[fast]];}let current=links[slow],previous=-1;links[slow]=-1;while(current!==-1){const following=links[current];links[current]=previous;previous=current;current=following;trace({nodes,links,current,previous});}let first=0,second=previous;while(second!==-1){const a=links[first],b=links[second];links[first]=second;links[second]=a;trace({nodes,links,current:first});first=a;second=b;}return walk(nodes,links,0);`,
"copy-random-list":`const nodes=d.values,copies=[];for(let current=0;current<nodes.length;current++){copies.push([nodes[current],d.random[current]]);trace({nodes,current,copies});}return copies;`,
"reverse-k-group":`const nodes=d.values,links=makeLinks(nodes.length),k=d.k;if(k<1)throw Error('k must be positive');let head=nodes.length?0:-1,tail=-1,current=head;while(current!==-1){let end=current;for(let i=1;i<k&&end!==-1;i++)end=links[end];if(end===-1)break;const following=links[end],start=current;let previous=following;while(current!==following){const next=links[current];links[current]=previous;previous=current;current=next;trace({nodes,links,current,previous});}if(tail===-1)head=end;else links[tail]=end;tail=start;trace({nodes,links,head,tail});}return walk(nodes,links,head);`,
"search-matrix":`const {matrix,target}=d;if(!matrix.length||!matrix[0].length)return false;const cols=matrix[0].length;let left=0,right=matrix.length*cols-1;while(left<=right){const mid=Math.floor((left+right)/2),row=Math.floor(mid/cols),col=mid%cols;trace({matrix,row,col,left,right});if(matrix[row][col]===target)return true;if(matrix[row][col]<target)left=mid+1;else right=mid-1;}return false;`,
"koko-bananas":`const nums=d.piles,hours=d.h;let left=1,right=Math.max(...nums);while(left<right){const mid=Math.floor((left+right)/2),needed=nums.reduce((sum,v)=>sum+Math.ceil(v/mid),0);trace({nums,left,right,mid,needed});if(needed<=hours)right=mid;else left=mid+1;}return left;`,
"median-sorted-arrays":`let a=d.nums1,b=d.nums2;if(a.length>b.length)[a,b]=[b,a];if(!b.length)throw Error('Both arrays empty');let left=0,right=a.length;const half=Math.floor((a.length+b.length+1)/2);while(left<=right){const i=Math.floor((left+right)/2),j=half-i,al=i?a[i-1]:-Infinity,ar=i<a.length?a[i]:Infinity,bl=j?b[j-1]:-Infinity,br=j<b.length?b[j]:Infinity;trace({a,b,i,j});if(al<=br&&bl<=ar)return (a.length+b.length)%2?Math.max(al,bl):(Math.max(al,bl)+Math.min(ar,br))/2;if(al>br)right=i-1;else left=i+1;}throw Error('Inputs must be sorted');`,
"minimum-rotated":`const {nums}=d;let left=0,right=nums.length-1;while(left<right){const mid=Math.floor((left+right)/2);trace({nums,left,right,mid});if(nums[mid]>nums[right])left=mid+1;else right=mid;}return nums[left];`,
"search-rotated":`const {nums,target}=d;let left=0,right=nums.length-1;while(left<=right){const mid=Math.floor((left+right)/2);trace({nums,left,right,mid});if(nums[mid]===target)return mid;if(nums[left]<=nums[mid]){if(nums[left]<=target&&target<nums[mid])right=mid-1;else left=mid+1;}else{if(nums[mid]<target&&target<=nums[right])left=mid+1;else right=mid-1;}}return -1;`,
"search-rotated-duplicates":`const {nums,target}=d;let left=0,right=nums.length-1;while(left<=right){const mid=Math.floor((left+right)/2);trace({nums,left,right,mid});if(nums[mid]===target)return true;if(nums[left]===nums[mid]&&nums[mid]===nums[right]){left++;right--;}else if(nums[left]<=nums[mid]){if(nums[left]<=target&&target<nums[mid])right=mid-1;else left=mid+1;}else{if(nums[mid]<target&&target<=nums[right])left=mid+1;else right=mid-1;}}return false;`,
"mountain-array":`const {nums,target}=d;let left=0,right=nums.length-1;while(left<right){const mid=Math.floor((left+right)/2);trace({nums,left,right,mid});if(nums[mid]<nums[mid+1])left=mid+1;else right=mid;}const peak=left;for(let side=0;side<2;side++){left=side?peak+1:0;right=side?nums.length-1:peak;while(left<=right){const mid=Math.floor((left+right)/2);trace({nums,left,right,mid,peak});if(nums[mid]===target)return mid;if((nums[mid]<target)!==Boolean(side))left=mid+1;else right=mid-1;}}return -1;`,
"level-order":`const {nodes,left_child,right_child}=makeTree(d.tree),queue=nodes.length?[0]:[],result=[];while(queue.length){const level=[];let count=queue.length;while(count--){const current=queue.shift();level.push(nodes[current]);for(const child of [left_child[current],right_child[current]])if(child!==-1)queue.push(child);trace({nodes,left_child,right_child,queue,current});}result.push(level);}return result;`,
"right-side-view":`const {nodes,left_child,right_child}=makeTree(d.tree),queue=nodes.length?[0]:[],result=[];while(queue.length){let count=queue.length,current;while(count--){current=queue.shift();for(const child of [left_child[current],right_child[current]])if(child!==-1)queue.push(child);trace({nodes,left_child,right_child,queue,current});}result.push(nodes[current]);}return result;`,
"next-right-pointers":`const {nodes,left_child,right_child}=makeTree(d.tree),queue=nodes.length?[0]:[],links=Array(nodes.length).fill(-1);while(queue.length){let count=queue.length,previous=-1;while(count--){const current=queue.shift();if(previous!==-1)links[previous]=current;previous=current;for(const child of [left_child[current],right_child[current]])if(child!==-1)queue.push(child);trace({nodes,left_child,right_child,links,current});}}return nodes.map((v,i)=>[v,links[i]===-1?null:nodes[links[i]]]);`,
"word-ladder":`const begin=d.beginWord,end=d.endWord,words=new Set(d.wordList);if(!words.has(end))return 0;const queue=[[begin,1]],visited=new Set([begin]),edges=[];while(queue.length){const [current,distance]=queue.shift();trace({edges,current,queue,visited});if(current===end)return distance;for(const word of [...words].sort()){if(word.length!==current.length)continue;const diff=[...word].filter((c,i)=>c!==current[i]).length;if(diff===1&&!visited.has(word)){visited.add(word);edges.push([current,word]);queue.push([word,distance+1]);}}}return 0;`,
"maximum-depth":`const {nodes,left_child,right_child}=makeTree(d.tree);function visit(current){if(current===-1)return 0;const depth=1+Math.max(visit(left_child[current]),visit(right_child[current]));trace({nodes,left_child,right_child,current,depth});return depth;}return visit(nodes.length?0:-1);`,
"lowest-common-ancestor":`const {nodes,left_child,right_child}=makeTree(d.tree);function visit(current){if(current===-1)return -1;trace({nodes,left_child,right_child,current});if(nodes[current]===d.p||nodes[current]===d.q)return current;const a=visit(left_child[current]),b=visit(right_child[current]);return a!==-1&&b!==-1?current:a!==-1?a:b;}const answer=visit(nodes.length?0:-1);return answer===-1?null:nodes[answer];`,
"tree-diameter":`const {nodes,left_child,right_child}=makeTree(d.tree);let best=0;function visit(current){if(current===-1)return 0;const a=visit(left_child[current]),b=visit(right_child[current]);best=Math.max(best,a+b);trace({nodes,left_child,right_child,current,best});return 1+Math.max(a,b);}visit(nodes.length?0:-1);return best;`,
"maximum-path-sum":`const {nodes,left_child,right_child}=makeTree(d.tree);if(!nodes.length)return 0;let best=-Infinity;function gain(current){if(current===-1)return 0;const a=Math.max(0,gain(left_child[current])),b=Math.max(0,gain(right_child[current]));best=Math.max(best,nodes[current]+a+b);trace({nodes,left_child,right_child,current,best});return nodes[current]+Math.max(a,b);}gain(0);return best;`,
"implement-trie":`const trie=Object.create(null),result=[];for(const [name,word]of d.operations){let node=trie;for(const c of word){if(name==='insert')node[c]??=Object.create(null);if(!(c in node)){node=null;break;}node=node[c];}if(name==='insert'){node.$=true;result.push(null);}else result.push(node!==null&&(name==='startsWith'||!!node.$));trace({trie,result,word});}return result;`,
"word-dictionary":`const trie=Object.create(null),result=[];function search(node,word,i){if(i===word.length)return !!node.$;const c=word[i];if(c==='.')return Object.entries(node).some(([key,child])=>key!=='$'&&search(child,word,i+1));return c in node&&search(node[c],word,i+1);}for(const [name,word]of d.operations){if(name==='addWord'){let node=trie;for(const c of word){node[c]??=Object.create(null);node=node[c];}node.$=true;result.push(null);}else result.push(search(trie,word,0));trace({trie,result,word});}return result;`,
"replace-words":`const trie=Object.create(null),result=[];for(const root of d.dictionary){let node=trie;for(const c of root){node[c]??=Object.create(null);node=node[c];}node.$=true;}for(const word of d.sentence.trim().split(/\\s+/)){let node=trie,prefix='';for(const c of word){if(node.$||!(c in node))break;prefix+=c;node=node[c];}result.push(node.$?prefix:word);trace({trie,word,result});}return result.join(' ');`,
"word-search-ii":`const grid=d.board.map(row=>[...row]),trie=Object.create(null),found=new Set();for(const word of d.words){let node=trie;for(const c of word){node[c]??=Object.create(null);node=node[c];}node.$=word;}const rows=grid.length,cols=grid[0]?.length??0;function visit(row,col,node){if(row<0||col<0||row>=rows||col>=cols)return;const c=grid[row][col];if(!(c in node))return;const next=node[c];if(next.$)found.add(next.$);grid[row][col]='#';trace({grid,row,col,found});visit(row+1,col,next);visit(row-1,col,next);visit(row,col+1,next);visit(row,col-1,next);grid[row][col]=c;}for(let r=0;r<rows;r++)for(let c=0;c<cols;c++)visit(r,c,trie);return [...found].sort();`,
"missing-number":`const nums=[...d.nums];for(let i=0;i<nums.length;i++){while(nums[i]>=0&&nums[i]<nums.length&&nums[i]!==i){const j=nums[i];if(nums[j]===nums[i])break;[nums[i],nums[j]]=[nums[j],nums[i]];trace({nums,i,j});}}for(let i=0;i<nums.length;i++)if(nums[i]!==i)return i;return nums.length;`,
"disappeared-numbers":`const nums=[...d.nums],result=[];for(let i=0;i<nums.length;i++){while(nums[i]>=1&&nums[i]<=nums.length&&nums[nums[i]-1]!==nums[i]){const j=nums[i]-1;[nums[i],nums[j]]=[nums[j],nums[i]];trace({nums,i,j});}}for(let i=0;i<nums.length;i++)if(nums[i]!==i+1)result.push(i+1);return result;`,
"set-mismatch":`const nums=[...d.nums];for(let i=0;i<nums.length;i++){trace({nums,i});while(nums[nums[i]-1]!==nums[i]){const j=nums[i]-1;[nums[i],nums[j]]=[nums[j],nums[i]];trace({nums,i,j});}}for(let i=0;i<nums.length;i++)if(nums[i]!==i+1)return [nums[i],i+1];return [];`,
"first-missing-positive":`const nums=[...d.nums];for(let i=0;i<nums.length;i++){while(nums[i]>0&&nums[i]<=nums.length&&nums[nums[i]-1]!==nums[i]){const j=nums[i]-1;[nums[i],nums[j]]=[nums[j],nums[i]];trace({nums,i,j});}}for(let i=0;i<nums.length;i++)if(nums[i]!==i+1)return i+1;return nums.length+1;`,
};
const helpers=`// Index-based links make pointer changes visible.
function makeLinks(n,pos=-1) { return Array.from({length:n},(_,i)=>i+1<n?i+1:pos); }
function walk(nodes,links,head) { const result=[],seen=new Set(); while(head!==-1&&!seen.has(head)){seen.add(head);result.push(nodes[head]);head=links[head];}return result; }
function makeTree(values) {
    const nodes=[],left_child=[],right_child=[];
    if(!values.length||values[0]===null)return {nodes,left_child,right_child};
    nodes.push(values[0]);left_child.push(-1);right_child.push(-1);
    const queue=[0];let index=1;
    while(queue.length&&index<values.length){const parent=queue.shift();for(const children of [left_child,right_child]){if(index>=values.length)break;const value=values[index++];if(value!==null){children[parent]=nodes.length;queue.push(nodes.length);nodes.push(value);left_child.push(-1);right_child.push(-1);}}}
    return {nodes,left_child,right_child};
}
// Binary heap: before(a,b) is true when a belongs nearer the root.
class Heap {
    constructor(before=(a,b)=>a<b){this.values=[];this.before=before;}
    push(value){const a=this.values;a.push(value);let i=a.length-1;while(i){const p=(i-1)>>1;if(!this.before(a[i],a[p]))break;[a[i],a[p]]=[a[p],a[i]];i=p;}}
    pop(){const a=this.values;if(!a.length)return undefined;const root=a[0],last=a.pop();if(a.length){a[0]=last;let i=0;while(true){let best=i;for(const c of [2*i+1,2*i+2])if(c<a.length&&this.before(a[c],a[best]))best=c;if(best===i)break;[a[i],a[best]]=[a[best],a[i]];i=best;}}return root;}
    get size(){return this.values.length;}
    get top(){return this.values[0];}
}
`;
function support(body:string){
 let prefix='';
 if(body.includes('makeLinks('))prefix+=helpers.slice(0,helpers.indexOf('function walk'));
 if(body.includes('walk('))prefix+=helpers.slice(helpers.indexOf('function walk'),helpers.indexOf('function makeTree'));
 if(body.includes('makeTree('))prefix+=helpers.slice(helpers.indexOf('function makeTree'),helpers.indexOf('// Binary heap'));
 if(body.includes('new Heap('))prefix+=helpers.slice(helpers.indexOf('// Binary heap'));
 return prefix;
}
export const javascriptSolutions:Record<string,string>=Object.fromEntries(Object.entries({...bodies,...javascriptAdvanced}).map(([id,body])=>[id,support(body)+"\nfunction solve(d) {\n"+body.split("\n").map(line=>"    "+line).join("\n")+"\n}\n"]));
