"use client";
import {useState} from 'react';
import {motion,useReducedMotion} from 'motion/react';
const demos={
 'maximum-average-subarray':{name:'Sliding window',idea:'Keep a running total as a fixed-size window moves.',when:'Use it for contiguous groups of a fixed length.',trap:'Start with the first real window—not zero—so negative numbers work too.',values:[1,12,-5,-6,50,3],steps:[{active:[0,1,2,3],labels:{0:'left',3:'right'},text:'Start with four adjacent values.',math:'1 + 12 − 5 − 6 = 2'},{active:[1,2,3,4],labels:{0:'leaves',1:'left',4:'enters'},text:'Move one place. Subtract the outgoing value and add the incoming one.',math:'2 − 1 + 50 = 51'},{active:[2,3,4,5],labels:{1:'leaves',2:'left',5:'enters'},text:'Repeat. Keep the best sum seen so far, then divide it by four.',math:'51 − 12 + 3 = 42 · best average: 51 ÷ 4 = 12.75'}]},
 'two-sum-sorted':{name:'Two pointers',idea:'Compare two ends, then move the pointer that can improve the sum.',when:'Use this rule when the values are sorted and you need a target pair.',trap:'Do not use the same element twice. This problem returns positions starting at 1.',values:[2,7,11,15],steps:[{active:[0,3],labels:{0:'left',3:'right'},text:'Target: 9. The sum is too large, so move the right pointer left.',math:'2 + 15 = 17 > 9'},{active:[0,2],labels:{0:'left',2:'right'},text:'Still too large. A smaller right value can reduce the sum.',math:'2 + 11 = 13 > 9'},{active:[0,1],labels:{0:'left',1:'right'},text:'Found the pair. Indices 0 and 1 become positions 1 and 2.',math:'2 + 7 = 9'}]},
 'binary-search-standard':{name:'Binary search',idea:'Compare the middle value and eliminate half the candidates.',when:'Use it when sorted order tells you which half can contain the target.',trap:'Move past the checked middle: left = mid + 1 or right = mid − 1.',values:[1,3,5,7,9,11,13],steps:[{active:[0,1,2,3,4,5,6],labels:{0:'left',3:'mid',6:'right'},text:'Target: 11. The middle is too small, so discard indices 0 through 3.',math:'7 < 11 → search right'},{active:[4,5,6],labels:{4:'left',5:'mid',6:'right'},text:'Only three candidates remain. Compare their middle value.',math:'11 = 11 → found index 5'}]}
};
export function ConceptIntro({id}:{id:string}){
 const [step,setStep]=useState(0),reduced=useReducedMotion();
 const demo=demos[id as keyof typeof demos];if(!demo)return null;
 const current=demo.steps[step];
 return <details className="concept-intro" open><summary>Understand the idea · {demo.name}<span>A tiny example before the code</span></summary><div className="concept-intro-content"><div><h2>{demo.idea}</h2><p><b>When it helps</b> {demo.when}</p><p><b>Watch out</b> {demo.trap}</p><small>Illustration only · your selected input runs below.</small></div><div className="concept-demo"><div className="concept-demo-cells">{demo.values.map((value,i)=><motion.div key={i} animate={{opacity:current.active.includes(i)?1:.5}} transition={{duration:reduced?0:.3}} className={current.active.includes(i)?'selected':''}><small>{i}</small><strong>{value}</strong><span>{(current.labels as Record<number,string|undefined>)[i]&&<motion.em layoutId={`${id}-${(current.labels as Record<number,string|undefined>)[i]}`} transition={{duration:reduced?0:.35}}>{(current.labels as Record<number,string|undefined>)[i]}</motion.em>}</span></motion.div>)}</div><div className="concept-demo-story" aria-live="polite"><p>{current.text}</p><code>{current.math}</code></div><nav aria-label="Concept demo steps"><button disabled={step===0} onClick={()=>setStep(s=>s-1)}>← Back</button><span>{step+1} / {demo.steps.length}</span><button onClick={()=>setStep(s=>(s+1)%demo.steps.length)}>{step===demo.steps.length-1?'Replay ↺':'Next step →'}</button></nav></div></div></details>;
}
